<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/static/h-ui/css/H-ui.css" />
<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/static/h-ui.admin/css/style.css" />
<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/lib/icheck/icheck.css" />
<link rel="stylesheet" type="text/css" href="${ly}/js/H-ui.admin_v3.0/lib/lightbox2/2.8.1/css/lightbox.css" />
<link href="${ly}/js/H-ui.admin_v3.0/static/h-ui.admin/css/H-ui.login.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="${ly}/styles/universal.css" />
<link rel="stylesheet" type="text/css" href="${ly}/styles/common.css" />

<script type="text/javascript" src="${ly}/js/H-ui.admin_v3.0/lib/jquery/1.9.1/jquery.min.js"></script> 
<script type="text/javascript" src="${ly}/js/H-ui.admin_v3.0/static/h-ui/js/H-ui.min.js"></script> 
<script type="text/javascript" src="${ly}/js/H-ui.admin_v3.0/static/h-ui.admin/js/H-ui.admin.js"></script> 
<script type="text/javascript" src="${ly }/js/util/utils.js"></script>
<script type="text/javascript" src="${ly }/js/print.js"></script>
<script src="${ly }/js/jquery-migrate-1.2.1.min.js"></script>
<script src="${ly }/js/jquery.jqprint-0.3.js"></script>
<script type="text/javascript" src="${ly}/js/H-ui.admin_v3.0/lib/datatables/1.10.0/jquery.dataTables.min.js"></script> 