package com.spring.web.dao;

import com.spring.web.model.AFxjz;

public interface AFxjzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_fxjz_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_fxjz_tbl
     *
     * @mbggenerated
     */
    int insert(AFxjz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_fxjz_tbl
     *
     * @mbggenerated
     */
    int insertSelective(AFxjz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_fxjz_tbl
     *
     * @mbggenerated
     */
    AFxjz selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_fxjz_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AFxjz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_fxjz_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AFxjz record);
}