package com.spring.web.dao;

import org.apache.ibatis.annotations.Param;
import com.spring.web.model.AGwyj;

public interface AGwyjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_tbl
     *
     * @mbggenerated
     */
    int insert(AGwyj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_tbl
     *
     * @mbggenerated
     */
    int insertSelective(AGwyj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_tbl
     *
     * @mbggenerated
     */
    AGwyj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AGwyj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AGwyj record);
    
    AGwyj selectByDepartId(@Param("departId") Integer departId);
}