package com.spring.web.dao;

import com.spring.web.model.CompanyIskey;

public interface CompanyIskeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_iskey_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_iskey_tbl
     *
     * @mbggenerated
     */
    int insert(CompanyIskey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_iskey_tbl
     *
     * @mbggenerated
     */
    int insertSelective(CompanyIskey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_iskey_tbl
     *
     * @mbggenerated
     */
    CompanyIskey selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_iskey_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyIskey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_iskey_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyIskey record);
}