package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import com.spring.web.model.DangerLib;

public interface DangerLibMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_lib_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_lib_tbl
     *
     * @mbggenerated
     */
    int insert(DangerLib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_lib_tbl
     *
     * @mbggenerated
     */
    int insertSelective(DangerLib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_lib_tbl
     *
     * @mbggenerated
     */
    DangerLib selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_lib_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DangerLib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_lib_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DangerLib record);

    /** 
    * @param m 
     * @return 
    */
    List<DangerLib> selectDangerList(Map<String, Object> m);
}