package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import com.spring.web.ibatis.DynamicParameter;
import com.spring.web.model.District;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table district_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table district_tbl
     *
     * @mbggenerated
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table district_tbl
     *
     * @mbggenerated
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table district_tbl
     *
     * @mbggenerated
     */
    District selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table district_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table district_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(District record);

    District selectByName(District d);

    List<DynamicParameter<String, Object>> selectList(Map<String, Object> m);
    
    /** 
     * @param
     * @return 
     */
    List<DynamicParameter<String, Object>> selectDistrict();

    /**
     * 根据区级id查询所有的镇
     * @param
     * @return
     */
    List<Map<String, Object>> selectByDistrivtId();

    /**
     * 区级用户登陆获取详细信息
     * @param id
     * @return
     */
    Map selectParticularByUid(Integer id);
}