package com.spring.web.dao;

import java.util.List;

import com.spring.web.model.FcBlindplatePermit;

public interface FcBlindplatePermitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_blindplate_permit_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_blindplate_permit_t
     *
     * @mbggenerated
     */
    int insert(FcBlindplatePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_blindplate_permit_t
     *
     * @mbggenerated
     */
    int insertSelective(FcBlindplatePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_blindplate_permit_t
     *
     * @mbggenerated
     */
    FcBlindplatePermit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_blindplate_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FcBlindplatePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_blindplate_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FcBlindplatePermit record);
    
    List<FcBlindplatePermit> selectByUid(Integer uid);
}