package com.spring.web.dao;

import java.util.List;

import com.spring.web.model.FcBrokenlandPermit;

public interface FcBrokenlandPermitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    int insert(FcBrokenlandPermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    int insertSelective(FcBrokenlandPermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    FcBrokenlandPermit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FcBrokenlandPermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FcBrokenlandPermit record);
    
	List<FcBrokenlandPermit> selectByUid(Integer uid);
}