package com.spring.web.dao;

import java.util.Map;

import com.spring.web.model.FcTemporaryDangerItem;

public interface FcTemporaryDangerItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_temporarydanger_item_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_temporarydanger_item_t
     *
     * @mbggenerated
     */
    int insert(FcTemporaryDangerItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_temporarydanger_item_t
     *
     * @mbggenerated
     */
    int insertSelective(FcTemporaryDangerItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_temporarydanger_item_t
     *
     * @mbggenerated
     */
    FcTemporaryDangerItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_temporarydanger_item_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FcTemporaryDangerItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_temporarydanger_item_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FcTemporaryDangerItem record);
    
    int insertBath(Map<String, Object> m);
}