package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import com.spring.web.model.Pequipment;

public interface PequipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pequipment_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pequipment_tbl
     *
     * @mbggenerated
     */
    int insert(Pequipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pequipment_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Pequipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pequipment_tbl
     *
     * @mbggenerated
     */
    Pequipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pequipment_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pequipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pequipment_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pequipment record);
    
    List<Map<String, Object>> selectByMap(Map<String, Object> m);
    
    int insertBatch(Map<String, Object> m);
}