package com.spring.web.dao;

import com.spring.web.model.PushMessage;

public interface PushMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message_tbl
     *
     * @mbggenerated
     */
    int insert(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message_tbl
     *
     * @mbggenerated
     */
    int insertSelective(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message_tbl
     *
     * @mbggenerated
     */
    PushMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PushMessage record);
}