package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import com.spring.web.model.PushMess;

public interface PushMessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_mess_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_mess_tbl
     *
     * @mbggenerated
     */
    int insert(PushMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_mess_tbl
     *
     * @mbggenerated
     */
    int insertSelective(PushMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_mess_tbl
     *
     * @mbggenerated
     */
    PushMess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_mess_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PushMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_mess_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PushMess record);
    
    /**
     * 根据公告ID查询推送信息
    * @param noticeId
    * @return
     */
    PushMess selectByNoticeId(Integer noticeId);
    
    /**
     * 根据用户ID查询推送的公告信息
    * @param m
    * @return
     */
    List<Map<String, Object>> selectNotice(Map<String, Object> m);
}