package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import com.spring.web.ibatis.DynamicParameter;
import com.spring.web.model.Sperson;
import com.spring.web.model.User;

public interface SpersonMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sperson_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sperson_tbl
     *
     * @mbggenerated
     */
    int insert(Sperson record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sperson_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Sperson record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sperson_tbl
     *
     * @mbggenerated
     */
    Sperson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sperson_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sperson record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sperson_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sperson record);

    /**
     * @return
     */
    List<DynamicParameter<String, Object>> selectSpersonList(Map<String, Object> m);

    /**
     * @param map
     * @return
     */
    int insertBatch(Map<String, Object> map);
    
    /**
     * 批量导入持证上岗人员名单
     * @param list
     * @return
     */
    int insertSpersonBatch(@Param("list") List<Sperson> list);
    
    /**
     * 查询企业下所有人员
     */
    List<Sperson> selectAllUser(Map<String, Object> map);
    
    List<DynamicParameter<String, Object>> selectClique(Map<String, Object> m);
}