package com.spring.web.dao;

import com.spring.web.model.Table;

public interface TableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_tbl
     *
     * @mbggenerated
     */
    int insert(Table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_tbl
     *
     * @mbggenerated
     */
    Table selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Table record);

    /** 
    * @param isType 
     * @return 
    */
    Table selectByIsType(Integer isType);
}