package com.spring.web.dao;

import com.spring.web.model.TCompany;

public interface TCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_tbl
     *
     * @mbggenerated
     */
    int insert(TCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_tbl
     *
     * @mbggenerated
     */
    int insertSelective(TCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_tbl
     *
     * @mbggenerated
     */
    TCompany selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCompany record);
}