package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import com.spring.web.model.TItem;

public interface TItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    int insert(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    int insertSelective(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    TItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TItem record);
    
    List<TItem> selectByIndustry(@Param("industryId") Integer industryId);
    
    List<TItem> selectByLevelIds(@Param("levelIds") String levelIds);
    
    List<Map<String, Object>> selectByLevelIdsModel(@Param("levelIds") String levelIds);
    
    
    
}