package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import com.spring.web.model.TModel;

public interface TModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    int insert(TModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    int insertSelective(TModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    TModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TModel record);
    
    List<Map<String, Object>> selectByMap(Map<String, Object> m);
    
    List<Map<String, Object>> selectByMap1(Map<String, Object> m);//检索条件增加，检查周期
    
    List<Map<String, Object>> selectByMap2(Map<String, Object> m);//检索条件增加，检查周期不为1
    
    List<TModel> selectAuto();

    /**
     * 根据公司id查询所有的模版信息
     * @param uid
     * @return
     */
    List<Map<Integer, String>> selectModelByUid(Integer uid);
}