package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import com.spring.web.ibatis.DynamicParameter;
import com.spring.web.model.Town;
import org.apache.ibatis.annotations.Param;

public interface TownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_tbl
     *
     * @mbggenerated
     */
    int insert(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_tbl
     *
     * @mbggenerated
     */
    Town selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Town record);

    /** 
    * @return 
    */
    List<DynamicParameter<String, Object>> selectTownList(Map<String, Object> m);
    
    Town selectByName(Town record);
    
    /** 
     * 批量跟新townid
    * @return 
    */
    int updTown(Map<String, Object> m);
    
    int updTownNull(Map<String, Object> m);
    
    List<Map<String, Object>> selectListByDistrict(Map<String, Object> m);
    
    /** 
     * @param
     * @return 
     */
    List<Map<String, Object>> selectTown();

    /**
     * 更据区获取镇
     * @param id
     * @return
     */
    List<Map<String, Object>> selectByDistrictId(Integer id);

    /**
     * 镇级用户登陆获取详细信息
     * @param id
     * @return
     */
    Map selectParticularByUid(Integer id);

    List<Town> findAll(@Param("districtId") Integer districtId);
}