package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import com.spring.web.model.TRecheckItem;

public interface TRecheckItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    int insert(TRecheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    int insertSelective(TRecheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    TRecheckItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRecheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRecheckItem record);
    
    int insertBath(Map<String, Object> m);
    
    List<Map<String, Object>> selectByCheckId(@Param("checkId") Integer checkId);

    /**
     * 根据checkItemId查询数据
     * @param id
     * @return
     */
    TRecheckItem selectByCheckItemId(Integer id);

    List<Map<String, Object>> selectByCheckIdtwo(Integer checkId);
}