package com.spring.web.dao;

import java.util.List;
import com.spring.web.model.TTindustry;

public interface TTindustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tindustry_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tindustry_tbl
     *
     * @mbggenerated
     */
    int insert(TTindustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tindustry_tbl
     *
     * @mbggenerated
     */
    int insertSelective(TTindustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tindustry_tbl
     *
     * @mbggenerated
     */
    TTindustry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tindustry_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TTindustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tindustry_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TTindustry record);
    
    List<TTindustry> selectAll();
}