package com.spring.web.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import com.spring.web.ibatis.DynamicParameter;
import com.spring.web.ibatis.LlHashMap;
import com.spring.web.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /** 
    * @param username
    * @return 
    */
    User selectUserByUserName(String userName);

    /** 
    * @param m
    * @return 
    */
    List<DynamicParameter<String, Object>> selectCompany(Map<String, Object> m);
    
    /**
     * 查询所有用户
     */
    List<User> selectAllUser();
    
    List<Map<String, Object>> selectCompanyFromView(Map<String, Object> m);
    
    /**
     * 查询所有用户
     */
    Integer selectAllUser5(@Param("companyName") String companyName);

    /** 
    * @param m
    * @return 获取没有经纬度的企业
    */
    List<User> selectJwd();
    
}