package com.spring.web.dao;

import java.util.List;
import java.util.Map;

import com.spring.web.model.YzHighTemperature;
import com.spring.web.model.YzLiquidAmmonia;

public interface YzHighTemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_hightemperature_permit_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_hightemperature_permit_t
     *
     * @mbggenerated
     */
    int insert(YzHighTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_hightemperature_permit_t
     *
     * @mbggenerated
     */
    int insertSelective(YzHighTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_hightemperature_permit_t
     *
     * @mbggenerated
     */
    YzHighTemperature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_hightemperature_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YzHighTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_hightemperature_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YzHighTemperature record);
    
    List<YzHighTemperature> selectByUid(Integer uid);
    
    Integer selectCount(List<Integer> m);
    
    List<Integer> selectUidsByList(List<Integer> m);
}