package com.spring.web.dao;

import java.util.List;

import com.spring.web.model.FcLimitspacePermit;
import com.spring.web.model.YzLiquidAmmonia;

public interface YzLiquidAmmoniaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    int insert(YzLiquidAmmonia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    int insertSelective(YzLiquidAmmonia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    YzLiquidAmmonia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YzLiquidAmmonia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YzLiquidAmmonia record);
    
    List<YzLiquidAmmonia> selectByUid(Integer uid);
    
    Integer selectCount(List<Integer> m);
    
    List<Integer> selectUidsByList(List<Integer> m);

//    List<YzLiquidAmmonia> selectByUidAll(Integer uid);
    
//    YzLiquidAmmonia selectByUid(Integer id);
    
}