package com.spring.web.dao;

import java.util.List;
import java.util.Map;

import com.spring.web.model.YzMajorEquipment;
import com.spring.web.model.YzSpecialEquipment;

public interface YzSpecialEquipmentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_specialequipment_t
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_specialequipment_t
	 * @mbggenerated
	 */
	int insert(YzSpecialEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_specialequipment_t
	 * @mbggenerated
	 */
	int insertSelective(YzSpecialEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_specialequipment_t
	 * @mbggenerated
	 */
	YzSpecialEquipment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_specialequipment_t
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(YzSpecialEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_specialequipment_t
	 * @mbggenerated
	 */
	int updateByPrimaryKey(YzSpecialEquipment record);

	List<YzSpecialEquipment> selectByUserId(Map<String, Object> map);

}