package com.spring.web.dao;

import java.util.List;
import java.util.Map;

import com.spring.web.model.YzStiveExplosion;
import com.spring.web.model.YzTradeArder;

public interface YzTradeArderMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	int insert(YzTradeArder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	int insertSelective(YzTradeArder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	YzTradeArder selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(YzTradeArder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	int updateByPrimaryKey(YzTradeArder record);

	List<YzTradeArder> selectByUid(Integer uid);
	
	Integer selectCount(List<Integer> m);
	
	List<Integer> selectUidsByList(List<Integer> m);
	
}