package com.spring.web.model;

public class AGwyjSh {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_gwyj_sh_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_gwyj_sh_tbl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_gwyj_sh_tbl.measures
     *
     * @mbggenerated
     */
    private String measures;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_sh_tbl
     *
     * @mbggenerated
     */
    public AGwyjSh(Integer id, String name, String measures) {
        this.id = id;
        this.name = name;
        this.measures = measures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_sh_tbl
     *
     * @mbggenerated
     */
    public AGwyjSh() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_gwyj_sh_tbl.id
     *
     * @return the value of a_gwyj_sh_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_gwyj_sh_tbl.id
     *
     * @param id the value for a_gwyj_sh_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_gwyj_sh_tbl.name
     *
     * @return the value of a_gwyj_sh_tbl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_gwyj_sh_tbl.name
     *
     * @param name the value for a_gwyj_sh_tbl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_gwyj_sh_tbl.measures
     *
     * @return the value of a_gwyj_sh_tbl.measures
     *
     * @mbggenerated
     */
    public String getMeasures() {
        return measures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_gwyj_sh_tbl.measures
     *
     * @param measures the value for a_gwyj_sh_tbl.measures
     *
     * @mbggenerated
     */
    public void setMeasures(String measures) {
        this.measures = measures == null ? null : measures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_sh_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AGwyjSh other = (AGwyjSh) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMeasures() == null ? other.getMeasures() == null : this.getMeasures().equals(other.getMeasures()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_sh_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMeasures() == null) ? 0 : getMeasures().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_gwyj_sh_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", measures=").append(measures);
        sb.append("]");
        return sb.toString();
    }
}