package com.spring.web.model;

public class AMaterial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.fzs
     *
     * @mbggenerated
     */
    private String fzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.cas
     *
     * @mbggenerated
     */
    private String cas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.un
     *
     * @mbggenerated
     */
    private String un;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.fzl
     *
     * @mbggenerated
     */
    private String fzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wh_wg
     *
     * @mbggenerated
     */
    private String whWg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wh_rd
     *
     * @mbggenerated
     */
    private String whRd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wh_fd
     *
     * @mbggenerated
     */
    private String whFd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wh_md
     *
     * @mbggenerated
     */
    private String whMd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wh_bhzqy
     *
     * @mbggenerated
     */
    private String whBhzqy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wh_rjx
     *
     * @mbggenerated
     */
    private String whRjx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.wx
     *
     * @mbggenerated
     */
    private String wx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_rsx
     *
     * @mbggenerated
     */
    private String rsRsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_hxfj
     *
     * @mbggenerated
     */
    private String rsHxfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_sd
     *
     * @mbggenerated
     */
    private String rsSd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_zrd
     *
     * @mbggenerated
     */
    private String rsZrd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_bz_min
     *
     * @mbggenerated
     */
    private String rsBzMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_bz_max
     *
     * @mbggenerated
     */
    private String rsBzMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_lb
     *
     * @mbggenerated
     */
    private String rsLb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_wdx
     *
     * @mbggenerated
     */
    private String rsWdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_jhwh
     *
     * @mbggenerated
     */
    private String rsJhwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_jjw
     *
     * @mbggenerated
     */
    private String rsJjw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.rs_mhff
     *
     * @mbggenerated
     */
    private String rsMhff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_jcjx_zg
     *
     * @mbggenerated
     */
    private String dxJcjxZg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_jcjx_mg
     *
     * @mbggenerated
     */
    private String dxJcjxMg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_jcjx_qsl
     *
     * @mbggenerated
     */
    private String dxJcjxQsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_jcjx_mg2
     *
     * @mbggenerated
     */
    private String dxJcjxMg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_dx
     *
     * @mbggenerated
     */
    private String dxDx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_dx2
     *
     * @mbggenerated
     */
    private String dxDx2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_dx3
     *
     * @mbggenerated
     */
    private String dxDx3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_qr
     *
     * @mbggenerated
     */
    private String dxQr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.dx_wh
     *
     * @mbggenerated
     */
    private String dxWh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.cy
     *
     * @mbggenerated
     */
    private String cy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_material_tbl.xlcz
     *
     * @mbggenerated
     */
    private String xlcz;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_material_tbl
     *
     * @mbggenerated
     */
    public AMaterial(Integer id, String name, String nameEn, String fzs, String cas, String un, String fzl, String serialNumber, String whWg, String whRd, String whFd, String whMd, String whBhzqy, String whRjx, String wx, String rsRsx, String rsHxfj, String rsSd, String rsZrd, String rsBzMin, String rsBzMax, String rsLb, String rsWdx, String rsJhwh, String rsJjw, String rsMhff, String dxJcjxZg, String dxJcjxMg, String dxJcjxQsl, String dxJcjxMg2, String dxDx, String dxDx2, String dxDx3, String dxQr, String dxWh, String cy, String xlcz) {
        this.id = id;
        this.name = name;
        this.nameEn = nameEn;
        this.fzs = fzs;
        this.cas = cas;
        this.un = un;
        this.fzl = fzl;
        this.serialNumber = serialNumber;
        this.whWg = whWg;
        this.whRd = whRd;
        this.whFd = whFd;
        this.whMd = whMd;
        this.whBhzqy = whBhzqy;
        this.whRjx = whRjx;
        this.wx = wx;
        this.rsRsx = rsRsx;
        this.rsHxfj = rsHxfj;
        this.rsSd = rsSd;
        this.rsZrd = rsZrd;
        this.rsBzMin = rsBzMin;
        this.rsBzMax = rsBzMax;
        this.rsLb = rsLb;
        this.rsWdx = rsWdx;
        this.rsJhwh = rsJhwh;
        this.rsJjw = rsJjw;
        this.rsMhff = rsMhff;
        this.dxJcjxZg = dxJcjxZg;
        this.dxJcjxMg = dxJcjxMg;
        this.dxJcjxQsl = dxJcjxQsl;
        this.dxJcjxMg2 = dxJcjxMg2;
        this.dxDx = dxDx;
        this.dxDx2 = dxDx2;
        this.dxDx3 = dxDx3;
        this.dxQr = dxQr;
        this.dxWh = dxWh;
        this.cy = cy;
        this.xlcz = xlcz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_material_tbl
     *
     * @mbggenerated
     */
    public AMaterial() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.id
     *
     * @return the value of a_material_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.id
     *
     * @param id the value for a_material_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.name
     *
     * @return the value of a_material_tbl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.name
     *
     * @param name the value for a_material_tbl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.name_en
     *
     * @return the value of a_material_tbl.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.name_en
     *
     * @param nameEn the value for a_material_tbl.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.fzs
     *
     * @return the value of a_material_tbl.fzs
     *
     * @mbggenerated
     */
    public String getFzs() {
        return fzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.fzs
     *
     * @param fzs the value for a_material_tbl.fzs
     *
     * @mbggenerated
     */
    public void setFzs(String fzs) {
        this.fzs = fzs == null ? null : fzs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.cas
     *
     * @return the value of a_material_tbl.cas
     *
     * @mbggenerated
     */
    public String getCas() {
        return cas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.cas
     *
     * @param cas the value for a_material_tbl.cas
     *
     * @mbggenerated
     */
    public void setCas(String cas) {
        this.cas = cas == null ? null : cas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.un
     *
     * @return the value of a_material_tbl.un
     *
     * @mbggenerated
     */
    public String getUn() {
        return un;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.un
     *
     * @param un the value for a_material_tbl.un
     *
     * @mbggenerated
     */
    public void setUn(String un) {
        this.un = un == null ? null : un.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.fzl
     *
     * @return the value of a_material_tbl.fzl
     *
     * @mbggenerated
     */
    public String getFzl() {
        return fzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.fzl
     *
     * @param fzl the value for a_material_tbl.fzl
     *
     * @mbggenerated
     */
    public void setFzl(String fzl) {
        this.fzl = fzl == null ? null : fzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.serial_number
     *
     * @return the value of a_material_tbl.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.serial_number
     *
     * @param serialNumber the value for a_material_tbl.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wh_wg
     *
     * @return the value of a_material_tbl.wh_wg
     *
     * @mbggenerated
     */
    public String getWhWg() {
        return whWg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wh_wg
     *
     * @param whWg the value for a_material_tbl.wh_wg
     *
     * @mbggenerated
     */
    public void setWhWg(String whWg) {
        this.whWg = whWg == null ? null : whWg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wh_rd
     *
     * @return the value of a_material_tbl.wh_rd
     *
     * @mbggenerated
     */
    public String getWhRd() {
        return whRd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wh_rd
     *
     * @param whRd the value for a_material_tbl.wh_rd
     *
     * @mbggenerated
     */
    public void setWhRd(String whRd) {
        this.whRd = whRd == null ? null : whRd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wh_fd
     *
     * @return the value of a_material_tbl.wh_fd
     *
     * @mbggenerated
     */
    public String getWhFd() {
        return whFd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wh_fd
     *
     * @param whFd the value for a_material_tbl.wh_fd
     *
     * @mbggenerated
     */
    public void setWhFd(String whFd) {
        this.whFd = whFd == null ? null : whFd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wh_md
     *
     * @return the value of a_material_tbl.wh_md
     *
     * @mbggenerated
     */
    public String getWhMd() {
        return whMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wh_md
     *
     * @param whMd the value for a_material_tbl.wh_md
     *
     * @mbggenerated
     */
    public void setWhMd(String whMd) {
        this.whMd = whMd == null ? null : whMd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wh_bhzqy
     *
     * @return the value of a_material_tbl.wh_bhzqy
     *
     * @mbggenerated
     */
    public String getWhBhzqy() {
        return whBhzqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wh_bhzqy
     *
     * @param whBhzqy the value for a_material_tbl.wh_bhzqy
     *
     * @mbggenerated
     */
    public void setWhBhzqy(String whBhzqy) {
        this.whBhzqy = whBhzqy == null ? null : whBhzqy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wh_rjx
     *
     * @return the value of a_material_tbl.wh_rjx
     *
     * @mbggenerated
     */
    public String getWhRjx() {
        return whRjx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wh_rjx
     *
     * @param whRjx the value for a_material_tbl.wh_rjx
     *
     * @mbggenerated
     */
    public void setWhRjx(String whRjx) {
        this.whRjx = whRjx == null ? null : whRjx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.wx
     *
     * @return the value of a_material_tbl.wx
     *
     * @mbggenerated
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.wx
     *
     * @param wx the value for a_material_tbl.wx
     *
     * @mbggenerated
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_rsx
     *
     * @return the value of a_material_tbl.rs_rsx
     *
     * @mbggenerated
     */
    public String getRsRsx() {
        return rsRsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_rsx
     *
     * @param rsRsx the value for a_material_tbl.rs_rsx
     *
     * @mbggenerated
     */
    public void setRsRsx(String rsRsx) {
        this.rsRsx = rsRsx == null ? null : rsRsx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_hxfj
     *
     * @return the value of a_material_tbl.rs_hxfj
     *
     * @mbggenerated
     */
    public String getRsHxfj() {
        return rsHxfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_hxfj
     *
     * @param rsHxfj the value for a_material_tbl.rs_hxfj
     *
     * @mbggenerated
     */
    public void setRsHxfj(String rsHxfj) {
        this.rsHxfj = rsHxfj == null ? null : rsHxfj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_sd
     *
     * @return the value of a_material_tbl.rs_sd
     *
     * @mbggenerated
     */
    public String getRsSd() {
        return rsSd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_sd
     *
     * @param rsSd the value for a_material_tbl.rs_sd
     *
     * @mbggenerated
     */
    public void setRsSd(String rsSd) {
        this.rsSd = rsSd == null ? null : rsSd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_zrd
     *
     * @return the value of a_material_tbl.rs_zrd
     *
     * @mbggenerated
     */
    public String getRsZrd() {
        return rsZrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_zrd
     *
     * @param rsZrd the value for a_material_tbl.rs_zrd
     *
     * @mbggenerated
     */
    public void setRsZrd(String rsZrd) {
        this.rsZrd = rsZrd == null ? null : rsZrd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_bz_min
     *
     * @return the value of a_material_tbl.rs_bz_min
     *
     * @mbggenerated
     */
    public String getRsBzMin() {
        return rsBzMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_bz_min
     *
     * @param rsBzMin the value for a_material_tbl.rs_bz_min
     *
     * @mbggenerated
     */
    public void setRsBzMin(String rsBzMin) {
        this.rsBzMin = rsBzMin == null ? null : rsBzMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_bz_max
     *
     * @return the value of a_material_tbl.rs_bz_max
     *
     * @mbggenerated
     */
    public String getRsBzMax() {
        return rsBzMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_bz_max
     *
     * @param rsBzMax the value for a_material_tbl.rs_bz_max
     *
     * @mbggenerated
     */
    public void setRsBzMax(String rsBzMax) {
        this.rsBzMax = rsBzMax == null ? null : rsBzMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_lb
     *
     * @return the value of a_material_tbl.rs_lb
     *
     * @mbggenerated
     */
    public String getRsLb() {
        return rsLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_lb
     *
     * @param rsLb the value for a_material_tbl.rs_lb
     *
     * @mbggenerated
     */
    public void setRsLb(String rsLb) {
        this.rsLb = rsLb == null ? null : rsLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_wdx
     *
     * @return the value of a_material_tbl.rs_wdx
     *
     * @mbggenerated
     */
    public String getRsWdx() {
        return rsWdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_wdx
     *
     * @param rsWdx the value for a_material_tbl.rs_wdx
     *
     * @mbggenerated
     */
    public void setRsWdx(String rsWdx) {
        this.rsWdx = rsWdx == null ? null : rsWdx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_jhwh
     *
     * @return the value of a_material_tbl.rs_jhwh
     *
     * @mbggenerated
     */
    public String getRsJhwh() {
        return rsJhwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_jhwh
     *
     * @param rsJhwh the value for a_material_tbl.rs_jhwh
     *
     * @mbggenerated
     */
    public void setRsJhwh(String rsJhwh) {
        this.rsJhwh = rsJhwh == null ? null : rsJhwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_jjw
     *
     * @return the value of a_material_tbl.rs_jjw
     *
     * @mbggenerated
     */
    public String getRsJjw() {
        return rsJjw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_jjw
     *
     * @param rsJjw the value for a_material_tbl.rs_jjw
     *
     * @mbggenerated
     */
    public void setRsJjw(String rsJjw) {
        this.rsJjw = rsJjw == null ? null : rsJjw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.rs_mhff
     *
     * @return the value of a_material_tbl.rs_mhff
     *
     * @mbggenerated
     */
    public String getRsMhff() {
        return rsMhff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.rs_mhff
     *
     * @param rsMhff the value for a_material_tbl.rs_mhff
     *
     * @mbggenerated
     */
    public void setRsMhff(String rsMhff) {
        this.rsMhff = rsMhff == null ? null : rsMhff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_jcjx_zg
     *
     * @return the value of a_material_tbl.dx_jcjx_zg
     *
     * @mbggenerated
     */
    public String getDxJcjxZg() {
        return dxJcjxZg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_jcjx_zg
     *
     * @param dxJcjxZg the value for a_material_tbl.dx_jcjx_zg
     *
     * @mbggenerated
     */
    public void setDxJcjxZg(String dxJcjxZg) {
        this.dxJcjxZg = dxJcjxZg == null ? null : dxJcjxZg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_jcjx_mg
     *
     * @return the value of a_material_tbl.dx_jcjx_mg
     *
     * @mbggenerated
     */
    public String getDxJcjxMg() {
        return dxJcjxMg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_jcjx_mg
     *
     * @param dxJcjxMg the value for a_material_tbl.dx_jcjx_mg
     *
     * @mbggenerated
     */
    public void setDxJcjxMg(String dxJcjxMg) {
        this.dxJcjxMg = dxJcjxMg == null ? null : dxJcjxMg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_jcjx_qsl
     *
     * @return the value of a_material_tbl.dx_jcjx_qsl
     *
     * @mbggenerated
     */
    public String getDxJcjxQsl() {
        return dxJcjxQsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_jcjx_qsl
     *
     * @param dxJcjxQsl the value for a_material_tbl.dx_jcjx_qsl
     *
     * @mbggenerated
     */
    public void setDxJcjxQsl(String dxJcjxQsl) {
        this.dxJcjxQsl = dxJcjxQsl == null ? null : dxJcjxQsl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_jcjx_mg2
     *
     * @return the value of a_material_tbl.dx_jcjx_mg2
     *
     * @mbggenerated
     */
    public String getDxJcjxMg2() {
        return dxJcjxMg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_jcjx_mg2
     *
     * @param dxJcjxMg2 the value for a_material_tbl.dx_jcjx_mg2
     *
     * @mbggenerated
     */
    public void setDxJcjxMg2(String dxJcjxMg2) {
        this.dxJcjxMg2 = dxJcjxMg2 == null ? null : dxJcjxMg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_dx
     *
     * @return the value of a_material_tbl.dx_dx
     *
     * @mbggenerated
     */
    public String getDxDx() {
        return dxDx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_dx
     *
     * @param dxDx the value for a_material_tbl.dx_dx
     *
     * @mbggenerated
     */
    public void setDxDx(String dxDx) {
        this.dxDx = dxDx == null ? null : dxDx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_dx2
     *
     * @return the value of a_material_tbl.dx_dx2
     *
     * @mbggenerated
     */
    public String getDxDx2() {
        return dxDx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_dx2
     *
     * @param dxDx2 the value for a_material_tbl.dx_dx2
     *
     * @mbggenerated
     */
    public void setDxDx2(String dxDx2) {
        this.dxDx2 = dxDx2 == null ? null : dxDx2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_dx3
     *
     * @return the value of a_material_tbl.dx_dx3
     *
     * @mbggenerated
     */
    public String getDxDx3() {
        return dxDx3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_dx3
     *
     * @param dxDx3 the value for a_material_tbl.dx_dx3
     *
     * @mbggenerated
     */
    public void setDxDx3(String dxDx3) {
        this.dxDx3 = dxDx3 == null ? null : dxDx3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_qr
     *
     * @return the value of a_material_tbl.dx_qr
     *
     * @mbggenerated
     */
    public String getDxQr() {
        return dxQr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_qr
     *
     * @param dxQr the value for a_material_tbl.dx_qr
     *
     * @mbggenerated
     */
    public void setDxQr(String dxQr) {
        this.dxQr = dxQr == null ? null : dxQr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.dx_wh
     *
     * @return the value of a_material_tbl.dx_wh
     *
     * @mbggenerated
     */
    public String getDxWh() {
        return dxWh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.dx_wh
     *
     * @param dxWh the value for a_material_tbl.dx_wh
     *
     * @mbggenerated
     */
    public void setDxWh(String dxWh) {
        this.dxWh = dxWh == null ? null : dxWh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.cy
     *
     * @return the value of a_material_tbl.cy
     *
     * @mbggenerated
     */
    public String getCy() {
        return cy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.cy
     *
     * @param cy the value for a_material_tbl.cy
     *
     * @mbggenerated
     */
    public void setCy(String cy) {
        this.cy = cy == null ? null : cy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_material_tbl.xlcz
     *
     * @return the value of a_material_tbl.xlcz
     *
     * @mbggenerated
     */
    public String getXlcz() {
        return xlcz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_material_tbl.xlcz
     *
     * @param xlcz the value for a_material_tbl.xlcz
     *
     * @mbggenerated
     */
    public void setXlcz(String xlcz) {
        this.xlcz = xlcz == null ? null : xlcz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_material_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AMaterial other = (AMaterial) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNameEn() == null ? other.getNameEn() == null : this.getNameEn().equals(other.getNameEn()))
            && (this.getFzs() == null ? other.getFzs() == null : this.getFzs().equals(other.getFzs()))
            && (this.getCas() == null ? other.getCas() == null : this.getCas().equals(other.getCas()))
            && (this.getUn() == null ? other.getUn() == null : this.getUn().equals(other.getUn()))
            && (this.getFzl() == null ? other.getFzl() == null : this.getFzl().equals(other.getFzl()))
            && (this.getSerialNumber() == null ? other.getSerialNumber() == null : this.getSerialNumber().equals(other.getSerialNumber()))
            && (this.getWhWg() == null ? other.getWhWg() == null : this.getWhWg().equals(other.getWhWg()))
            && (this.getWhRd() == null ? other.getWhRd() == null : this.getWhRd().equals(other.getWhRd()))
            && (this.getWhFd() == null ? other.getWhFd() == null : this.getWhFd().equals(other.getWhFd()))
            && (this.getWhMd() == null ? other.getWhMd() == null : this.getWhMd().equals(other.getWhMd()))
            && (this.getWhBhzqy() == null ? other.getWhBhzqy() == null : this.getWhBhzqy().equals(other.getWhBhzqy()))
            && (this.getWhRjx() == null ? other.getWhRjx() == null : this.getWhRjx().equals(other.getWhRjx()))
            && (this.getWx() == null ? other.getWx() == null : this.getWx().equals(other.getWx()))
            && (this.getRsRsx() == null ? other.getRsRsx() == null : this.getRsRsx().equals(other.getRsRsx()))
            && (this.getRsHxfj() == null ? other.getRsHxfj() == null : this.getRsHxfj().equals(other.getRsHxfj()))
            && (this.getRsSd() == null ? other.getRsSd() == null : this.getRsSd().equals(other.getRsSd()))
            && (this.getRsZrd() == null ? other.getRsZrd() == null : this.getRsZrd().equals(other.getRsZrd()))
            && (this.getRsBzMin() == null ? other.getRsBzMin() == null : this.getRsBzMin().equals(other.getRsBzMin()))
            && (this.getRsBzMax() == null ? other.getRsBzMax() == null : this.getRsBzMax().equals(other.getRsBzMax()))
            && (this.getRsLb() == null ? other.getRsLb() == null : this.getRsLb().equals(other.getRsLb()))
            && (this.getRsWdx() == null ? other.getRsWdx() == null : this.getRsWdx().equals(other.getRsWdx()))
            && (this.getRsJhwh() == null ? other.getRsJhwh() == null : this.getRsJhwh().equals(other.getRsJhwh()))
            && (this.getRsJjw() == null ? other.getRsJjw() == null : this.getRsJjw().equals(other.getRsJjw()))
            && (this.getRsMhff() == null ? other.getRsMhff() == null : this.getRsMhff().equals(other.getRsMhff()))
            && (this.getDxJcjxZg() == null ? other.getDxJcjxZg() == null : this.getDxJcjxZg().equals(other.getDxJcjxZg()))
            && (this.getDxJcjxMg() == null ? other.getDxJcjxMg() == null : this.getDxJcjxMg().equals(other.getDxJcjxMg()))
            && (this.getDxJcjxQsl() == null ? other.getDxJcjxQsl() == null : this.getDxJcjxQsl().equals(other.getDxJcjxQsl()))
            && (this.getDxJcjxMg2() == null ? other.getDxJcjxMg2() == null : this.getDxJcjxMg2().equals(other.getDxJcjxMg2()))
            && (this.getDxDx() == null ? other.getDxDx() == null : this.getDxDx().equals(other.getDxDx()))
            && (this.getDxDx2() == null ? other.getDxDx2() == null : this.getDxDx2().equals(other.getDxDx2()))
            && (this.getDxDx3() == null ? other.getDxDx3() == null : this.getDxDx3().equals(other.getDxDx3()))
            && (this.getDxQr() == null ? other.getDxQr() == null : this.getDxQr().equals(other.getDxQr()))
            && (this.getDxWh() == null ? other.getDxWh() == null : this.getDxWh().equals(other.getDxWh()))
            && (this.getCy() == null ? other.getCy() == null : this.getCy().equals(other.getCy()))
            && (this.getXlcz() == null ? other.getXlcz() == null : this.getXlcz().equals(other.getXlcz()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_material_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNameEn() == null) ? 0 : getNameEn().hashCode());
        result = prime * result + ((getFzs() == null) ? 0 : getFzs().hashCode());
        result = prime * result + ((getCas() == null) ? 0 : getCas().hashCode());
        result = prime * result + ((getUn() == null) ? 0 : getUn().hashCode());
        result = prime * result + ((getFzl() == null) ? 0 : getFzl().hashCode());
        result = prime * result + ((getSerialNumber() == null) ? 0 : getSerialNumber().hashCode());
        result = prime * result + ((getWhWg() == null) ? 0 : getWhWg().hashCode());
        result = prime * result + ((getWhRd() == null) ? 0 : getWhRd().hashCode());
        result = prime * result + ((getWhFd() == null) ? 0 : getWhFd().hashCode());
        result = prime * result + ((getWhMd() == null) ? 0 : getWhMd().hashCode());
        result = prime * result + ((getWhBhzqy() == null) ? 0 : getWhBhzqy().hashCode());
        result = prime * result + ((getWhRjx() == null) ? 0 : getWhRjx().hashCode());
        result = prime * result + ((getWx() == null) ? 0 : getWx().hashCode());
        result = prime * result + ((getRsRsx() == null) ? 0 : getRsRsx().hashCode());
        result = prime * result + ((getRsHxfj() == null) ? 0 : getRsHxfj().hashCode());
        result = prime * result + ((getRsSd() == null) ? 0 : getRsSd().hashCode());
        result = prime * result + ((getRsZrd() == null) ? 0 : getRsZrd().hashCode());
        result = prime * result + ((getRsBzMin() == null) ? 0 : getRsBzMin().hashCode());
        result = prime * result + ((getRsBzMax() == null) ? 0 : getRsBzMax().hashCode());
        result = prime * result + ((getRsLb() == null) ? 0 : getRsLb().hashCode());
        result = prime * result + ((getRsWdx() == null) ? 0 : getRsWdx().hashCode());
        result = prime * result + ((getRsJhwh() == null) ? 0 : getRsJhwh().hashCode());
        result = prime * result + ((getRsJjw() == null) ? 0 : getRsJjw().hashCode());
        result = prime * result + ((getRsMhff() == null) ? 0 : getRsMhff().hashCode());
        result = prime * result + ((getDxJcjxZg() == null) ? 0 : getDxJcjxZg().hashCode());
        result = prime * result + ((getDxJcjxMg() == null) ? 0 : getDxJcjxMg().hashCode());
        result = prime * result + ((getDxJcjxQsl() == null) ? 0 : getDxJcjxQsl().hashCode());
        result = prime * result + ((getDxJcjxMg2() == null) ? 0 : getDxJcjxMg2().hashCode());
        result = prime * result + ((getDxDx() == null) ? 0 : getDxDx().hashCode());
        result = prime * result + ((getDxDx2() == null) ? 0 : getDxDx2().hashCode());
        result = prime * result + ((getDxDx3() == null) ? 0 : getDxDx3().hashCode());
        result = prime * result + ((getDxQr() == null) ? 0 : getDxQr().hashCode());
        result = prime * result + ((getDxWh() == null) ? 0 : getDxWh().hashCode());
        result = prime * result + ((getCy() == null) ? 0 : getCy().hashCode());
        result = prime * result + ((getXlcz() == null) ? 0 : getXlcz().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_material_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", nameEn=").append(nameEn);
        sb.append(", fzs=").append(fzs);
        sb.append(", cas=").append(cas);
        sb.append(", un=").append(un);
        sb.append(", fzl=").append(fzl);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", whWg=").append(whWg);
        sb.append(", whRd=").append(whRd);
        sb.append(", whFd=").append(whFd);
        sb.append(", whMd=").append(whMd);
        sb.append(", whBhzqy=").append(whBhzqy);
        sb.append(", whRjx=").append(whRjx);
        sb.append(", wx=").append(wx);
        sb.append(", rsRsx=").append(rsRsx);
        sb.append(", rsHxfj=").append(rsHxfj);
        sb.append(", rsSd=").append(rsSd);
        sb.append(", rsZrd=").append(rsZrd);
        sb.append(", rsBzMin=").append(rsBzMin);
        sb.append(", rsBzMax=").append(rsBzMax);
        sb.append(", rsLb=").append(rsLb);
        sb.append(", rsWdx=").append(rsWdx);
        sb.append(", rsJhwh=").append(rsJhwh);
        sb.append(", rsJjw=").append(rsJjw);
        sb.append(", rsMhff=").append(rsMhff);
        sb.append(", dxJcjxZg=").append(dxJcjxZg);
        sb.append(", dxJcjxMg=").append(dxJcjxMg);
        sb.append(", dxJcjxQsl=").append(dxJcjxQsl);
        sb.append(", dxJcjxMg2=").append(dxJcjxMg2);
        sb.append(", dxDx=").append(dxDx);
        sb.append(", dxDx2=").append(dxDx2);
        sb.append(", dxDx3=").append(dxDx3);
        sb.append(", dxQr=").append(dxQr);
        sb.append(", dxWh=").append(dxWh);
        sb.append(", cy=").append(cy);
        sb.append(", xlcz=").append(xlcz);
        sb.append("]");
        return sb.toString();
    }
}