package com.spring.web.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class FcBrokenlandPermit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.sqdw
     *
     * @mbggenerated
     */
    private String sqdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.sqr
     *
     * @mbggenerated
     */
    private String sqr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.zyzbh
     *
     * @mbggenerated
     */
    private String zyzbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.zydw
     *
     * @mbggenerated
     */
    private String zydw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.sjxgdw
     *
     * @mbggenerated
     */
    private String sjxgdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.dlyy
     *
     * @mbggenerated
     */
    private String dlyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.dlsj_s
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date dlsjS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.dlsj_e
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date dlsjE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.dldd
     *
     * @mbggenerated
     */
    private String dldd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.dlddqz
     *
     * @mbggenerated
     */
    private String dlddqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.dlddqzsj
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date dlddqzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.whbs
     *
     * @mbggenerated
     */
    private String whbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.qrr1
     *
     * @mbggenerated
     */
    private String qrr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.qrr2
     *
     * @mbggenerated
     */
    private String qrr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.qrr3
     *
     * @mbggenerated
     */
    private String qrr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.qrr4
     *
     * @mbggenerated
     */
    private String qrr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.qtaqcs
     *
     * @mbggenerated
     */
    private String qtaqcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.bzr
     *
     * @mbggenerated
     */
    private String bzr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ssaqjyr1
     *
     * @mbggenerated
     */
    private String ssaqjyr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ssaqjyr2
     *
     * @mbggenerated
     */
    private String ssaqjyr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ssaqjyr3
     *
     * @mbggenerated
     */
    private String ssaqjyr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.sqdwyj
     *
     * @mbggenerated
     */
    private String sqdwyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.sqdwqz
     *
     * @mbggenerated
     */
    private String sqdwqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.sqdwqzsj
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date sqdwqzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.zydwyj
     *
     * @mbggenerated
     */
    private String zydwyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.zydwqz
     *
     * @mbggenerated
     */
    private String zydwqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.zydwqzsj
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date zydwqzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ygbmyj
     *
     * @mbggenerated
     */
    private String ygbmyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ygbmqz
     *
     * @mbggenerated
     */
    private String ygbmqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ygbmqzsj
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date ygbmqzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.spbmyj
     *
     * @mbggenerated
     */
    private String spbmyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.spbmqz
     *
     * @mbggenerated
     */
    private String spbmqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.spbmqzsj
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date spbmqzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.wgysyj
     *
     * @mbggenerated
     */
    private String wgysyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.wgysqz
     *
     * @mbggenerated
     */
    private String wgysqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.wgysqzsj
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date wgysqzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_brokenland_permit_t.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    public FcBrokenlandPermit(Integer id, Integer uid, String sqdw, String sqr, String zyzbh, String zydw, String sjxgdw, String dlyy, Date dlsjS, Date dlsjE, String dldd, String dlddqz, Date dlddqzsj, String whbs, String qrr1, String qrr2, String qrr3, String qrr4, String qtaqcs, String bzr, String ssaqjyr1, String ssaqjyr2, String ssaqjyr3, String sqdwyj, String sqdwqz, Date sqdwqzsj, String zydwyj, String zydwqz, Date zydwqzsj, String ygbmyj, String ygbmqz, Date ygbmqzsj, String spbmyj, String spbmqz, Date spbmqzsj, String wgysyj, String wgysqz, Date wgysqzsj, Integer del, Date ctime) {
        this.id = id;
        this.uid = uid;
        this.sqdw = sqdw;
        this.sqr = sqr;
        this.zyzbh = zyzbh;
        this.zydw = zydw;
        this.sjxgdw = sjxgdw;
        this.dlyy = dlyy;
        this.dlsjS = dlsjS;
        this.dlsjE = dlsjE;
        this.dldd = dldd;
        this.dlddqz = dlddqz;
        this.dlddqzsj = dlddqzsj;
        this.whbs = whbs;
        this.qrr1 = qrr1;
        this.qrr2 = qrr2;
        this.qrr3 = qrr3;
        this.qrr4 = qrr4;
        this.qtaqcs = qtaqcs;
        this.bzr = bzr;
        this.ssaqjyr1 = ssaqjyr1;
        this.ssaqjyr2 = ssaqjyr2;
        this.ssaqjyr3 = ssaqjyr3;
        this.sqdwyj = sqdwyj;
        this.sqdwqz = sqdwqz;
        this.sqdwqzsj = sqdwqzsj;
        this.zydwyj = zydwyj;
        this.zydwqz = zydwqz;
        this.zydwqzsj = zydwqzsj;
        this.ygbmyj = ygbmyj;
        this.ygbmqz = ygbmqz;
        this.ygbmqzsj = ygbmqzsj;
        this.spbmyj = spbmyj;
        this.spbmqz = spbmqz;
        this.spbmqzsj = spbmqzsj;
        this.wgysyj = wgysyj;
        this.wgysqz = wgysqz;
        this.wgysqzsj = wgysqzsj;
        this.del = del;
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    public FcBrokenlandPermit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.id
     *
     * @return the value of fc_brokenland_permit_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.id
     *
     * @param id the value for fc_brokenland_permit_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.uid
     *
     * @return the value of fc_brokenland_permit_t.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.uid
     *
     * @param uid the value for fc_brokenland_permit_t.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.sqdw
     *
     * @return the value of fc_brokenland_permit_t.sqdw
     *
     * @mbggenerated
     */
    public String getSqdw() {
        return sqdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.sqdw
     *
     * @param sqdw the value for fc_brokenland_permit_t.sqdw
     *
     * @mbggenerated
     */
    public void setSqdw(String sqdw) {
        this.sqdw = sqdw == null ? null : sqdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.sqr
     *
     * @return the value of fc_brokenland_permit_t.sqr
     *
     * @mbggenerated
     */
    public String getSqr() {
        return sqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.sqr
     *
     * @param sqr the value for fc_brokenland_permit_t.sqr
     *
     * @mbggenerated
     */
    public void setSqr(String sqr) {
        this.sqr = sqr == null ? null : sqr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.zyzbh
     *
     * @return the value of fc_brokenland_permit_t.zyzbh
     *
     * @mbggenerated
     */
    public String getZyzbh() {
        return zyzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.zyzbh
     *
     * @param zyzbh the value for fc_brokenland_permit_t.zyzbh
     *
     * @mbggenerated
     */
    public void setZyzbh(String zyzbh) {
        this.zyzbh = zyzbh == null ? null : zyzbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.zydw
     *
     * @return the value of fc_brokenland_permit_t.zydw
     *
     * @mbggenerated
     */
    public String getZydw() {
        return zydw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.zydw
     *
     * @param zydw the value for fc_brokenland_permit_t.zydw
     *
     * @mbggenerated
     */
    public void setZydw(String zydw) {
        this.zydw = zydw == null ? null : zydw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.sjxgdw
     *
     * @return the value of fc_brokenland_permit_t.sjxgdw
     *
     * @mbggenerated
     */
    public String getSjxgdw() {
        return sjxgdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.sjxgdw
     *
     * @param sjxgdw the value for fc_brokenland_permit_t.sjxgdw
     *
     * @mbggenerated
     */
    public void setSjxgdw(String sjxgdw) {
        this.sjxgdw = sjxgdw == null ? null : sjxgdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.dlyy
     *
     * @return the value of fc_brokenland_permit_t.dlyy
     *
     * @mbggenerated
     */
    public String getDlyy() {
        return dlyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.dlyy
     *
     * @param dlyy the value for fc_brokenland_permit_t.dlyy
     *
     * @mbggenerated
     */
    public void setDlyy(String dlyy) {
        this.dlyy = dlyy == null ? null : dlyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.dlsj_s
     *
     * @return the value of fc_brokenland_permit_t.dlsj_s
     *
     * @mbggenerated
     */
    public Date getDlsjS() {
        return dlsjS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.dlsj_s
     *
     * @param dlsjS the value for fc_brokenland_permit_t.dlsj_s
     *
     * @mbggenerated
     */
    public void setDlsjS(Date dlsjS) {
        this.dlsjS = dlsjS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.dlsj_e
     *
     * @return the value of fc_brokenland_permit_t.dlsj_e
     *
     * @mbggenerated
     */
    public Date getDlsjE() {
        return dlsjE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.dlsj_e
     *
     * @param dlsjE the value for fc_brokenland_permit_t.dlsj_e
     *
     * @mbggenerated
     */
    public void setDlsjE(Date dlsjE) {
        this.dlsjE = dlsjE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.dldd
     *
     * @return the value of fc_brokenland_permit_t.dldd
     *
     * @mbggenerated
     */
    public String getDldd() {
        return dldd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.dldd
     *
     * @param dldd the value for fc_brokenland_permit_t.dldd
     *
     * @mbggenerated
     */
    public void setDldd(String dldd) {
        this.dldd = dldd == null ? null : dldd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.dlddqz
     *
     * @return the value of fc_brokenland_permit_t.dlddqz
     *
     * @mbggenerated
     */
    public String getDlddqz() {
        return dlddqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.dlddqz
     *
     * @param dlddqz the value for fc_brokenland_permit_t.dlddqz
     *
     * @mbggenerated
     */
    public void setDlddqz(String dlddqz) {
        this.dlddqz = dlddqz == null ? null : dlddqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.dlddqzsj
     *
     * @return the value of fc_brokenland_permit_t.dlddqzsj
     *
     * @mbggenerated
     */
    public Date getDlddqzsj() {
        return dlddqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.dlddqzsj
     *
     * @param dlddqzsj the value for fc_brokenland_permit_t.dlddqzsj
     *
     * @mbggenerated
     */
    public void setDlddqzsj(Date dlddqzsj) {
        this.dlddqzsj = dlddqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.whbs
     *
     * @return the value of fc_brokenland_permit_t.whbs
     *
     * @mbggenerated
     */
    public String getWhbs() {
        return whbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.whbs
     *
     * @param whbs the value for fc_brokenland_permit_t.whbs
     *
     * @mbggenerated
     */
    public void setWhbs(String whbs) {
        this.whbs = whbs == null ? null : whbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.qrr1
     *
     * @return the value of fc_brokenland_permit_t.qrr1
     *
     * @mbggenerated
     */
    public String getQrr1() {
        return qrr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.qrr1
     *
     * @param qrr1 the value for fc_brokenland_permit_t.qrr1
     *
     * @mbggenerated
     */
    public void setQrr1(String qrr1) {
        this.qrr1 = qrr1 == null ? null : qrr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.qrr2
     *
     * @return the value of fc_brokenland_permit_t.qrr2
     *
     * @mbggenerated
     */
    public String getQrr2() {
        return qrr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.qrr2
     *
     * @param qrr2 the value for fc_brokenland_permit_t.qrr2
     *
     * @mbggenerated
     */
    public void setQrr2(String qrr2) {
        this.qrr2 = qrr2 == null ? null : qrr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.qrr3
     *
     * @return the value of fc_brokenland_permit_t.qrr3
     *
     * @mbggenerated
     */
    public String getQrr3() {
        return qrr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.qrr3
     *
     * @param qrr3 the value for fc_brokenland_permit_t.qrr3
     *
     * @mbggenerated
     */
    public void setQrr3(String qrr3) {
        this.qrr3 = qrr3 == null ? null : qrr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.qrr4
     *
     * @return the value of fc_brokenland_permit_t.qrr4
     *
     * @mbggenerated
     */
    public String getQrr4() {
        return qrr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.qrr4
     *
     * @param qrr4 the value for fc_brokenland_permit_t.qrr4
     *
     * @mbggenerated
     */
    public void setQrr4(String qrr4) {
        this.qrr4 = qrr4 == null ? null : qrr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.qtaqcs
     *
     * @return the value of fc_brokenland_permit_t.qtaqcs
     *
     * @mbggenerated
     */
    public String getQtaqcs() {
        return qtaqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.qtaqcs
     *
     * @param qtaqcs the value for fc_brokenland_permit_t.qtaqcs
     *
     * @mbggenerated
     */
    public void setQtaqcs(String qtaqcs) {
        this.qtaqcs = qtaqcs == null ? null : qtaqcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.bzr
     *
     * @return the value of fc_brokenland_permit_t.bzr
     *
     * @mbggenerated
     */
    public String getBzr() {
        return bzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.bzr
     *
     * @param bzr the value for fc_brokenland_permit_t.bzr
     *
     * @mbggenerated
     */
    public void setBzr(String bzr) {
        this.bzr = bzr == null ? null : bzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ssaqjyr1
     *
     * @return the value of fc_brokenland_permit_t.ssaqjyr1
     *
     * @mbggenerated
     */
    public String getSsaqjyr1() {
        return ssaqjyr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ssaqjyr1
     *
     * @param ssaqjyr1 the value for fc_brokenland_permit_t.ssaqjyr1
     *
     * @mbggenerated
     */
    public void setSsaqjyr1(String ssaqjyr1) {
        this.ssaqjyr1 = ssaqjyr1 == null ? null : ssaqjyr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ssaqjyr2
     *
     * @return the value of fc_brokenland_permit_t.ssaqjyr2
     *
     * @mbggenerated
     */
    public String getSsaqjyr2() {
        return ssaqjyr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ssaqjyr2
     *
     * @param ssaqjyr2 the value for fc_brokenland_permit_t.ssaqjyr2
     *
     * @mbggenerated
     */
    public void setSsaqjyr2(String ssaqjyr2) {
        this.ssaqjyr2 = ssaqjyr2 == null ? null : ssaqjyr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ssaqjyr3
     *
     * @return the value of fc_brokenland_permit_t.ssaqjyr3
     *
     * @mbggenerated
     */
    public String getSsaqjyr3() {
        return ssaqjyr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ssaqjyr3
     *
     * @param ssaqjyr3 the value for fc_brokenland_permit_t.ssaqjyr3
     *
     * @mbggenerated
     */
    public void setSsaqjyr3(String ssaqjyr3) {
        this.ssaqjyr3 = ssaqjyr3 == null ? null : ssaqjyr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.sqdwyj
     *
     * @return the value of fc_brokenland_permit_t.sqdwyj
     *
     * @mbggenerated
     */
    public String getSqdwyj() {
        return sqdwyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.sqdwyj
     *
     * @param sqdwyj the value for fc_brokenland_permit_t.sqdwyj
     *
     * @mbggenerated
     */
    public void setSqdwyj(String sqdwyj) {
        this.sqdwyj = sqdwyj == null ? null : sqdwyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.sqdwqz
     *
     * @return the value of fc_brokenland_permit_t.sqdwqz
     *
     * @mbggenerated
     */
    public String getSqdwqz() {
        return sqdwqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.sqdwqz
     *
     * @param sqdwqz the value for fc_brokenland_permit_t.sqdwqz
     *
     * @mbggenerated
     */
    public void setSqdwqz(String sqdwqz) {
        this.sqdwqz = sqdwqz == null ? null : sqdwqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.sqdwqzsj
     *
     * @return the value of fc_brokenland_permit_t.sqdwqzsj
     *
     * @mbggenerated
     */
    public Date getSqdwqzsj() {
        return sqdwqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.sqdwqzsj
     *
     * @param sqdwqzsj the value for fc_brokenland_permit_t.sqdwqzsj
     *
     * @mbggenerated
     */
    public void setSqdwqzsj(Date sqdwqzsj) {
        this.sqdwqzsj = sqdwqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.zydwyj
     *
     * @return the value of fc_brokenland_permit_t.zydwyj
     *
     * @mbggenerated
     */
    public String getZydwyj() {
        return zydwyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.zydwyj
     *
     * @param zydwyj the value for fc_brokenland_permit_t.zydwyj
     *
     * @mbggenerated
     */
    public void setZydwyj(String zydwyj) {
        this.zydwyj = zydwyj == null ? null : zydwyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.zydwqz
     *
     * @return the value of fc_brokenland_permit_t.zydwqz
     *
     * @mbggenerated
     */
    public String getZydwqz() {
        return zydwqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.zydwqz
     *
     * @param zydwqz the value for fc_brokenland_permit_t.zydwqz
     *
     * @mbggenerated
     */
    public void setZydwqz(String zydwqz) {
        this.zydwqz = zydwqz == null ? null : zydwqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.zydwqzsj
     *
     * @return the value of fc_brokenland_permit_t.zydwqzsj
     *
     * @mbggenerated
     */
    public Date getZydwqzsj() {
        return zydwqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.zydwqzsj
     *
     * @param zydwqzsj the value for fc_brokenland_permit_t.zydwqzsj
     *
     * @mbggenerated
     */
    public void setZydwqzsj(Date zydwqzsj) {
        this.zydwqzsj = zydwqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ygbmyj
     *
     * @return the value of fc_brokenland_permit_t.ygbmyj
     *
     * @mbggenerated
     */
    public String getYgbmyj() {
        return ygbmyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ygbmyj
     *
     * @param ygbmyj the value for fc_brokenland_permit_t.ygbmyj
     *
     * @mbggenerated
     */
    public void setYgbmyj(String ygbmyj) {
        this.ygbmyj = ygbmyj == null ? null : ygbmyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ygbmqz
     *
     * @return the value of fc_brokenland_permit_t.ygbmqz
     *
     * @mbggenerated
     */
    public String getYgbmqz() {
        return ygbmqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ygbmqz
     *
     * @param ygbmqz the value for fc_brokenland_permit_t.ygbmqz
     *
     * @mbggenerated
     */
    public void setYgbmqz(String ygbmqz) {
        this.ygbmqz = ygbmqz == null ? null : ygbmqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ygbmqzsj
     *
     * @return the value of fc_brokenland_permit_t.ygbmqzsj
     *
     * @mbggenerated
     */
    public Date getYgbmqzsj() {
        return ygbmqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ygbmqzsj
     *
     * @param ygbmqzsj the value for fc_brokenland_permit_t.ygbmqzsj
     *
     * @mbggenerated
     */
    public void setYgbmqzsj(Date ygbmqzsj) {
        this.ygbmqzsj = ygbmqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.spbmyj
     *
     * @return the value of fc_brokenland_permit_t.spbmyj
     *
     * @mbggenerated
     */
    public String getSpbmyj() {
        return spbmyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.spbmyj
     *
     * @param spbmyj the value for fc_brokenland_permit_t.spbmyj
     *
     * @mbggenerated
     */
    public void setSpbmyj(String spbmyj) {
        this.spbmyj = spbmyj == null ? null : spbmyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.spbmqz
     *
     * @return the value of fc_brokenland_permit_t.spbmqz
     *
     * @mbggenerated
     */
    public String getSpbmqz() {
        return spbmqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.spbmqz
     *
     * @param spbmqz the value for fc_brokenland_permit_t.spbmqz
     *
     * @mbggenerated
     */
    public void setSpbmqz(String spbmqz) {
        this.spbmqz = spbmqz == null ? null : spbmqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.spbmqzsj
     *
     * @return the value of fc_brokenland_permit_t.spbmqzsj
     *
     * @mbggenerated
     */
    public Date getSpbmqzsj() {
        return spbmqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.spbmqzsj
     *
     * @param spbmqzsj the value for fc_brokenland_permit_t.spbmqzsj
     *
     * @mbggenerated
     */
    public void setSpbmqzsj(Date spbmqzsj) {
        this.spbmqzsj = spbmqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.wgysyj
     *
     * @return the value of fc_brokenland_permit_t.wgysyj
     *
     * @mbggenerated
     */
    public String getWgysyj() {
        return wgysyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.wgysyj
     *
     * @param wgysyj the value for fc_brokenland_permit_t.wgysyj
     *
     * @mbggenerated
     */
    public void setWgysyj(String wgysyj) {
        this.wgysyj = wgysyj == null ? null : wgysyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.wgysqz
     *
     * @return the value of fc_brokenland_permit_t.wgysqz
     *
     * @mbggenerated
     */
    public String getWgysqz() {
        return wgysqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.wgysqz
     *
     * @param wgysqz the value for fc_brokenland_permit_t.wgysqz
     *
     * @mbggenerated
     */
    public void setWgysqz(String wgysqz) {
        this.wgysqz = wgysqz == null ? null : wgysqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.wgysqzsj
     *
     * @return the value of fc_brokenland_permit_t.wgysqzsj
     *
     * @mbggenerated
     */
    public Date getWgysqzsj() {
        return wgysqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.wgysqzsj
     *
     * @param wgysqzsj the value for fc_brokenland_permit_t.wgysqzsj
     *
     * @mbggenerated
     */
    public void setWgysqzsj(Date wgysqzsj) {
        this.wgysqzsj = wgysqzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.del
     *
     * @return the value of fc_brokenland_permit_t.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.del
     *
     * @param del the value for fc_brokenland_permit_t.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_brokenland_permit_t.ctime
     *
     * @return the value of fc_brokenland_permit_t.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_brokenland_permit_t.ctime
     *
     * @param ctime the value for fc_brokenland_permit_t.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FcBrokenlandPermit other = (FcBrokenlandPermit) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getSqdw() == null ? other.getSqdw() == null : this.getSqdw().equals(other.getSqdw()))
            && (this.getSqr() == null ? other.getSqr() == null : this.getSqr().equals(other.getSqr()))
            && (this.getZyzbh() == null ? other.getZyzbh() == null : this.getZyzbh().equals(other.getZyzbh()))
            && (this.getZydw() == null ? other.getZydw() == null : this.getZydw().equals(other.getZydw()))
            && (this.getSjxgdw() == null ? other.getSjxgdw() == null : this.getSjxgdw().equals(other.getSjxgdw()))
            && (this.getDlyy() == null ? other.getDlyy() == null : this.getDlyy().equals(other.getDlyy()))
            && (this.getDlsjS() == null ? other.getDlsjS() == null : this.getDlsjS().equals(other.getDlsjS()))
            && (this.getDlsjE() == null ? other.getDlsjE() == null : this.getDlsjE().equals(other.getDlsjE()))
            && (this.getDldd() == null ? other.getDldd() == null : this.getDldd().equals(other.getDldd()))
            && (this.getDlddqz() == null ? other.getDlddqz() == null : this.getDlddqz().equals(other.getDlddqz()))
            && (this.getDlddqzsj() == null ? other.getDlddqzsj() == null : this.getDlddqzsj().equals(other.getDlddqzsj()))
            && (this.getWhbs() == null ? other.getWhbs() == null : this.getWhbs().equals(other.getWhbs()))
            && (this.getQrr1() == null ? other.getQrr1() == null : this.getQrr1().equals(other.getQrr1()))
            && (this.getQrr2() == null ? other.getQrr2() == null : this.getQrr2().equals(other.getQrr2()))
            && (this.getQrr3() == null ? other.getQrr3() == null : this.getQrr3().equals(other.getQrr3()))
            && (this.getQrr4() == null ? other.getQrr4() == null : this.getQrr4().equals(other.getQrr4()))
            && (this.getQtaqcs() == null ? other.getQtaqcs() == null : this.getQtaqcs().equals(other.getQtaqcs()))
            && (this.getBzr() == null ? other.getBzr() == null : this.getBzr().equals(other.getBzr()))
            && (this.getSsaqjyr1() == null ? other.getSsaqjyr1() == null : this.getSsaqjyr1().equals(other.getSsaqjyr1()))
            && (this.getSsaqjyr2() == null ? other.getSsaqjyr2() == null : this.getSsaqjyr2().equals(other.getSsaqjyr2()))
            && (this.getSsaqjyr3() == null ? other.getSsaqjyr3() == null : this.getSsaqjyr3().equals(other.getSsaqjyr3()))
            && (this.getSqdwyj() == null ? other.getSqdwyj() == null : this.getSqdwyj().equals(other.getSqdwyj()))
            && (this.getSqdwqz() == null ? other.getSqdwqz() == null : this.getSqdwqz().equals(other.getSqdwqz()))
            && (this.getSqdwqzsj() == null ? other.getSqdwqzsj() == null : this.getSqdwqzsj().equals(other.getSqdwqzsj()))
            && (this.getZydwyj() == null ? other.getZydwyj() == null : this.getZydwyj().equals(other.getZydwyj()))
            && (this.getZydwqz() == null ? other.getZydwqz() == null : this.getZydwqz().equals(other.getZydwqz()))
            && (this.getZydwqzsj() == null ? other.getZydwqzsj() == null : this.getZydwqzsj().equals(other.getZydwqzsj()))
            && (this.getYgbmyj() == null ? other.getYgbmyj() == null : this.getYgbmyj().equals(other.getYgbmyj()))
            && (this.getYgbmqz() == null ? other.getYgbmqz() == null : this.getYgbmqz().equals(other.getYgbmqz()))
            && (this.getYgbmqzsj() == null ? other.getYgbmqzsj() == null : this.getYgbmqzsj().equals(other.getYgbmqzsj()))
            && (this.getSpbmyj() == null ? other.getSpbmyj() == null : this.getSpbmyj().equals(other.getSpbmyj()))
            && (this.getSpbmqz() == null ? other.getSpbmqz() == null : this.getSpbmqz().equals(other.getSpbmqz()))
            && (this.getSpbmqzsj() == null ? other.getSpbmqzsj() == null : this.getSpbmqzsj().equals(other.getSpbmqzsj()))
            && (this.getWgysyj() == null ? other.getWgysyj() == null : this.getWgysyj().equals(other.getWgysyj()))
            && (this.getWgysqz() == null ? other.getWgysqz() == null : this.getWgysqz().equals(other.getWgysqz()))
            && (this.getWgysqzsj() == null ? other.getWgysqzsj() == null : this.getWgysqzsj().equals(other.getWgysqzsj()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getSqdw() == null) ? 0 : getSqdw().hashCode());
        result = prime * result + ((getSqr() == null) ? 0 : getSqr().hashCode());
        result = prime * result + ((getZyzbh() == null) ? 0 : getZyzbh().hashCode());
        result = prime * result + ((getZydw() == null) ? 0 : getZydw().hashCode());
        result = prime * result + ((getSjxgdw() == null) ? 0 : getSjxgdw().hashCode());
        result = prime * result + ((getDlyy() == null) ? 0 : getDlyy().hashCode());
        result = prime * result + ((getDlsjS() == null) ? 0 : getDlsjS().hashCode());
        result = prime * result + ((getDlsjE() == null) ? 0 : getDlsjE().hashCode());
        result = prime * result + ((getDldd() == null) ? 0 : getDldd().hashCode());
        result = prime * result + ((getDlddqz() == null) ? 0 : getDlddqz().hashCode());
        result = prime * result + ((getDlddqzsj() == null) ? 0 : getDlddqzsj().hashCode());
        result = prime * result + ((getWhbs() == null) ? 0 : getWhbs().hashCode());
        result = prime * result + ((getQrr1() == null) ? 0 : getQrr1().hashCode());
        result = prime * result + ((getQrr2() == null) ? 0 : getQrr2().hashCode());
        result = prime * result + ((getQrr3() == null) ? 0 : getQrr3().hashCode());
        result = prime * result + ((getQrr4() == null) ? 0 : getQrr4().hashCode());
        result = prime * result + ((getQtaqcs() == null) ? 0 : getQtaqcs().hashCode());
        result = prime * result + ((getBzr() == null) ? 0 : getBzr().hashCode());
        result = prime * result + ((getSsaqjyr1() == null) ? 0 : getSsaqjyr1().hashCode());
        result = prime * result + ((getSsaqjyr2() == null) ? 0 : getSsaqjyr2().hashCode());
        result = prime * result + ((getSsaqjyr3() == null) ? 0 : getSsaqjyr3().hashCode());
        result = prime * result + ((getSqdwyj() == null) ? 0 : getSqdwyj().hashCode());
        result = prime * result + ((getSqdwqz() == null) ? 0 : getSqdwqz().hashCode());
        result = prime * result + ((getSqdwqzsj() == null) ? 0 : getSqdwqzsj().hashCode());
        result = prime * result + ((getZydwyj() == null) ? 0 : getZydwyj().hashCode());
        result = prime * result + ((getZydwqz() == null) ? 0 : getZydwqz().hashCode());
        result = prime * result + ((getZydwqzsj() == null) ? 0 : getZydwqzsj().hashCode());
        result = prime * result + ((getYgbmyj() == null) ? 0 : getYgbmyj().hashCode());
        result = prime * result + ((getYgbmqz() == null) ? 0 : getYgbmqz().hashCode());
        result = prime * result + ((getYgbmqzsj() == null) ? 0 : getYgbmqzsj().hashCode());
        result = prime * result + ((getSpbmyj() == null) ? 0 : getSpbmyj().hashCode());
        result = prime * result + ((getSpbmqz() == null) ? 0 : getSpbmqz().hashCode());
        result = prime * result + ((getSpbmqzsj() == null) ? 0 : getSpbmqzsj().hashCode());
        result = prime * result + ((getWgysyj() == null) ? 0 : getWgysyj().hashCode());
        result = prime * result + ((getWgysqz() == null) ? 0 : getWgysqz().hashCode());
        result = prime * result + ((getWgysqzsj() == null) ? 0 : getWgysqzsj().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_brokenland_permit_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", sqdw=").append(sqdw);
        sb.append(", sqr=").append(sqr);
        sb.append(", zyzbh=").append(zyzbh);
        sb.append(", zydw=").append(zydw);
        sb.append(", sjxgdw=").append(sjxgdw);
        sb.append(", dlyy=").append(dlyy);
        sb.append(", dlsjS=").append(dlsjS);
        sb.append(", dlsjE=").append(dlsjE);
        sb.append(", dldd=").append(dldd);
        sb.append(", dlddqz=").append(dlddqz);
        sb.append(", dlddqzsj=").append(dlddqzsj);
        sb.append(", whbs=").append(whbs);
        sb.append(", qrr1=").append(qrr1);
        sb.append(", qrr2=").append(qrr2);
        sb.append(", qrr3=").append(qrr3);
        sb.append(", qrr4=").append(qrr4);
        sb.append(", qtaqcs=").append(qtaqcs);
        sb.append(", bzr=").append(bzr);
        sb.append(", ssaqjyr1=").append(ssaqjyr1);
        sb.append(", ssaqjyr2=").append(ssaqjyr2);
        sb.append(", ssaqjyr3=").append(ssaqjyr3);
        sb.append(", sqdwyj=").append(sqdwyj);
        sb.append(", sqdwqz=").append(sqdwqz);
        sb.append(", sqdwqzsj=").append(sqdwqzsj);
        sb.append(", zydwyj=").append(zydwyj);
        sb.append(", zydwqz=").append(zydwqz);
        sb.append(", zydwqzsj=").append(zydwqzsj);
        sb.append(", ygbmyj=").append(ygbmyj);
        sb.append(", ygbmqz=").append(ygbmqz);
        sb.append(", ygbmqzsj=").append(ygbmqzsj);
        sb.append(", spbmyj=").append(spbmyj);
        sb.append(", spbmqz=").append(spbmqz);
        sb.append(", spbmqzsj=").append(spbmqzsj);
        sb.append(", wgysyj=").append(wgysyj);
        sb.append(", wgysqz=").append(wgysqz);
        sb.append(", wgysqzsj=").append(wgysqzsj);
        sb.append(", del=").append(del);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }
}