package com.spring.web.model;

public class FcNaturalDangerItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fc_naturaldanger_item_t.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fc_naturaldanger_item_t.dangerid
	 * @mbggenerated
	 */
	private Integer dangerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fc_naturaldanger_item_t.dangerstudyid
	 * @mbggenerated
	 */
	private Integer dangerstudyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fc_naturaldanger_item_t.checkret
	 * @mbggenerated
	 */
	private Integer checkret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fc_naturaldanger_item_t.img
	 * @mbggenerated
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fc_naturaldanger_item_t.checkret_bigd
	 * @mbggenerated
	 */
	private Integer checkretBigd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fc_naturaldanger_item_t
	 * @mbggenerated
	 */
	public FcNaturalDangerItem(Integer id, Integer dangerid,
			Integer dangerstudyid, Integer checkret, String img,
			Integer checkretBigd) {
		this.id = id;
		this.dangerid = dangerid;
		this.dangerstudyid = dangerstudyid;
		this.checkret = checkret;
		this.img = img;
		this.checkretBigd = checkretBigd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fc_naturaldanger_item_t
	 * @mbggenerated
	 */
	public FcNaturalDangerItem() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fc_naturaldanger_item_t.id
	 * @return  the value of fc_naturaldanger_item_t.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fc_naturaldanger_item_t.id
	 * @param id  the value for fc_naturaldanger_item_t.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fc_naturaldanger_item_t.dangerid
	 * @return  the value of fc_naturaldanger_item_t.dangerid
	 * @mbggenerated
	 */
	public Integer getDangerid() {
		return dangerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fc_naturaldanger_item_t.dangerid
	 * @param dangerid  the value for fc_naturaldanger_item_t.dangerid
	 * @mbggenerated
	 */
	public void setDangerid(Integer dangerid) {
		this.dangerid = dangerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fc_naturaldanger_item_t.dangerstudyid
	 * @return  the value of fc_naturaldanger_item_t.dangerstudyid
	 * @mbggenerated
	 */
	public Integer getDangerstudyid() {
		return dangerstudyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fc_naturaldanger_item_t.dangerstudyid
	 * @param dangerstudyid  the value for fc_naturaldanger_item_t.dangerstudyid
	 * @mbggenerated
	 */
	public void setDangerstudyid(Integer dangerstudyid) {
		this.dangerstudyid = dangerstudyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fc_naturaldanger_item_t.checkret
	 * @return  the value of fc_naturaldanger_item_t.checkret
	 * @mbggenerated
	 */
	public Integer getCheckret() {
		return checkret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fc_naturaldanger_item_t.checkret
	 * @param checkret  the value for fc_naturaldanger_item_t.checkret
	 * @mbggenerated
	 */
	public void setCheckret(Integer checkret) {
		this.checkret = checkret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fc_naturaldanger_item_t.img
	 * @return  the value of fc_naturaldanger_item_t.img
	 * @mbggenerated
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fc_naturaldanger_item_t.img
	 * @param img  the value for fc_naturaldanger_item_t.img
	 * @mbggenerated
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fc_naturaldanger_item_t.checkret_bigd
	 * @return  the value of fc_naturaldanger_item_t.checkret_bigd
	 * @mbggenerated
	 */
	public Integer getCheckretBigd() {
		return checkretBigd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fc_naturaldanger_item_t.checkret_bigd
	 * @param checkretBigd  the value for fc_naturaldanger_item_t.checkret_bigd
	 * @mbggenerated
	 */
	public void setCheckretBigd(Integer checkretBigd) {
		this.checkretBigd = checkretBigd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fc_naturaldanger_item_t
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		FcNaturalDangerItem other = (FcNaturalDangerItem) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getDangerid() == null ? other.getDangerid() == null
						: this.getDangerid().equals(other.getDangerid()))
				&& (this.getDangerstudyid() == null ? other.getDangerstudyid() == null
						: this.getDangerstudyid().equals(
								other.getDangerstudyid()))
				&& (this.getCheckret() == null ? other.getCheckret() == null
						: this.getCheckret().equals(other.getCheckret()))
				&& (this.getImg() == null ? other.getImg() == null : this
						.getImg().equals(other.getImg()))
				&& (this.getCheckretBigd() == null ? other.getCheckretBigd() == null
						: this.getCheckretBigd()
								.equals(other.getCheckretBigd()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fc_naturaldanger_item_t
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getDangerid() == null) ? 0 : getDangerid().hashCode());
		result = prime
				* result
				+ ((getDangerstudyid() == null) ? 0 : getDangerstudyid()
						.hashCode());
		result = prime * result
				+ ((getCheckret() == null) ? 0 : getCheckret().hashCode());
		result = prime * result
				+ ((getImg() == null) ? 0 : getImg().hashCode());
		result = prime
				* result
				+ ((getCheckretBigd() == null) ? 0 : getCheckretBigd()
						.hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fc_naturaldanger_item_t
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", dangerid=").append(dangerid);
		sb.append(", dangerstudyid=").append(dangerstudyid);
		sb.append(", checkret=").append(checkret);
		sb.append(", img=").append(img);
		sb.append(", checkretBigd=").append(checkretBigd);
		sb.append("]");
		return sb.toString();
	}
}