package com.spring.web.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class LightningProtection implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = 3883763525098915459L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.project
     *
     * @mbggenerated
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.last_test_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date lastTestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.expiration_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date expirationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.test_results
     *
     * @mbggenerated
     */
    private String testResults;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.detection_unit
     *
     * @mbggenerated
     */
    private String detectionUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.test_report_number
     *
     * @mbggenerated
     */
    private String testReportNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lightning_protection_tbl.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lightning_protection_tbl
     *
     * @mbggenerated
     */
    public LightningProtection(Integer id, Integer userId, String project, String content, Date lastTestTime, Date expirationTime, String testResults, String detectionUnit, String testReportNumber, String remark) {
        this.id = id;
        this.userId = userId;
        this.project = project;
        this.content = content;
        this.lastTestTime = lastTestTime;
        this.expirationTime = expirationTime;
        this.testResults = testResults;
        this.detectionUnit = detectionUnit;
        this.testReportNumber = testReportNumber;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lightning_protection_tbl
     *
     * @mbggenerated
     */
    public LightningProtection() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.id
     *
     * @return the value of lightning_protection_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.id
     *
     * @param id the value for lightning_protection_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.user_id
     *
     * @return the value of lightning_protection_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.user_id
     *
     * @param userId the value for lightning_protection_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.project
     *
     * @return the value of lightning_protection_tbl.project
     *
     * @mbggenerated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.project
     *
     * @param project the value for lightning_protection_tbl.project
     *
     * @mbggenerated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.content
     *
     * @return the value of lightning_protection_tbl.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.content
     *
     * @param content the value for lightning_protection_tbl.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.last_test_time
     *
     * @return the value of lightning_protection_tbl.last_test_time
     *
     * @mbggenerated
     */
    public Date getLastTestTime() {
        return lastTestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.last_test_time
     *
     * @param lastTestTime the value for lightning_protection_tbl.last_test_time
     *
     * @mbggenerated
     */
    public void setLastTestTime(Date lastTestTime) {
        this.lastTestTime = lastTestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.expiration_time
     *
     * @return the value of lightning_protection_tbl.expiration_time
     *
     * @mbggenerated
     */
    public Date getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.expiration_time
     *
     * @param expirationTime the value for lightning_protection_tbl.expiration_time
     *
     * @mbggenerated
     */
    public void setExpirationTime(Date expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.test_results
     *
     * @return the value of lightning_protection_tbl.test_results
     *
     * @mbggenerated
     */
    public String getTestResults() {
        return testResults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.test_results
     *
     * @param testResults the value for lightning_protection_tbl.test_results
     *
     * @mbggenerated
     */
    public void setTestResults(String testResults) {
        this.testResults = testResults == null ? null : testResults.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.detection_unit
     *
     * @return the value of lightning_protection_tbl.detection_unit
     *
     * @mbggenerated
     */
    public String getDetectionUnit() {
        return detectionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.detection_unit
     *
     * @param detectionUnit the value for lightning_protection_tbl.detection_unit
     *
     * @mbggenerated
     */
    public void setDetectionUnit(String detectionUnit) {
        this.detectionUnit = detectionUnit == null ? null : detectionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.test_report_number
     *
     * @return the value of lightning_protection_tbl.test_report_number
     *
     * @mbggenerated
     */
    public String getTestReportNumber() {
        return testReportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.test_report_number
     *
     * @param testReportNumber the value for lightning_protection_tbl.test_report_number
     *
     * @mbggenerated
     */
    public void setTestReportNumber(String testReportNumber) {
        this.testReportNumber = testReportNumber == null ? null : testReportNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lightning_protection_tbl.remark
     *
     * @return the value of lightning_protection_tbl.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lightning_protection_tbl.remark
     *
     * @param remark the value for lightning_protection_tbl.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lightning_protection_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LightningProtection other = (LightningProtection) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getProject() == null ? other.getProject() == null : this.getProject().equals(other.getProject()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getLastTestTime() == null ? other.getLastTestTime() == null : this.getLastTestTime().equals(other.getLastTestTime()))
            && (this.getExpirationTime() == null ? other.getExpirationTime() == null : this.getExpirationTime().equals(other.getExpirationTime()))
            && (this.getTestResults() == null ? other.getTestResults() == null : this.getTestResults().equals(other.getTestResults()))
            && (this.getDetectionUnit() == null ? other.getDetectionUnit() == null : this.getDetectionUnit().equals(other.getDetectionUnit()))
            && (this.getTestReportNumber() == null ? other.getTestReportNumber() == null : this.getTestReportNumber().equals(other.getTestReportNumber()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lightning_protection_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getProject() == null) ? 0 : getProject().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getLastTestTime() == null) ? 0 : getLastTestTime().hashCode());
        result = prime * result + ((getExpirationTime() == null) ? 0 : getExpirationTime().hashCode());
        result = prime * result + ((getTestResults() == null) ? 0 : getTestResults().hashCode());
        result = prime * result + ((getDetectionUnit() == null) ? 0 : getDetectionUnit().hashCode());
        result = prime * result + ((getTestReportNumber() == null) ? 0 : getTestReportNumber().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lightning_protection_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", project=").append(project);
        sb.append(", content=").append(content);
        sb.append(", lastTestTime=").append(lastTestTime);
        sb.append(", expirationTime=").append(expirationTime);
        sb.append(", testResults=").append(testResults);
        sb.append(", detectionUnit=").append(detectionUnit);
        sb.append(", testReportNumber=").append(testReportNumber);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}