package com.spring.web.model;

import java.io.Serializable;

public class ProductionProcessDiagram implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = 9056329567522596889L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.project
     *
     * @mbggenerated
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.material
     *
     * @mbggenerated
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.material_specifications
     *
     * @mbggenerated
     */
    private String materialSpecifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.personnel_requirements
     *
     * @mbggenerated
     */
    private String personnelRequirements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.inspection_standards
     *
     * @mbggenerated
     */
    private String inspectionStandards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.operating_rules
     *
     * @mbggenerated
     */
    private String operatingRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.equipment
     *
     * @mbggenerated
     */
    private String equipment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.doc_name
     *
     * @mbggenerated
     */
    private String docName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_process_diagram_tbl.doc_url
     *
     * @mbggenerated
     */
    private String docUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_process_diagram_tbl
     *
     * @mbggenerated
     */
    public ProductionProcessDiagram(Integer id, Integer userId, String project, String description, String material, String materialSpecifications, String personnelRequirements, String inspectionStandards, String operatingRules, String equipment, String docName, String docUrl) {
        this.id = id;
        this.userId = userId;
        this.project = project;
        this.description = description;
        this.material = material;
        this.materialSpecifications = materialSpecifications;
        this.personnelRequirements = personnelRequirements;
        this.inspectionStandards = inspectionStandards;
        this.operatingRules = operatingRules;
        this.equipment = equipment;
        this.docName = docName;
        this.docUrl = docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_process_diagram_tbl
     *
     * @mbggenerated
     */
    public ProductionProcessDiagram() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.id
     *
     * @return the value of production_process_diagram_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.id
     *
     * @param id the value for production_process_diagram_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.user_id
     *
     * @return the value of production_process_diagram_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.user_id
     *
     * @param userId the value for production_process_diagram_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.project
     *
     * @return the value of production_process_diagram_tbl.project
     *
     * @mbggenerated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.project
     *
     * @param project the value for production_process_diagram_tbl.project
     *
     * @mbggenerated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.description
     *
     * @return the value of production_process_diagram_tbl.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.description
     *
     * @param description the value for production_process_diagram_tbl.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.material
     *
     * @return the value of production_process_diagram_tbl.material
     *
     * @mbggenerated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.material
     *
     * @param material the value for production_process_diagram_tbl.material
     *
     * @mbggenerated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.material_specifications
     *
     * @return the value of production_process_diagram_tbl.material_specifications
     *
     * @mbggenerated
     */
    public String getMaterialSpecifications() {
        return materialSpecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.material_specifications
     *
     * @param materialSpecifications the value for production_process_diagram_tbl.material_specifications
     *
     * @mbggenerated
     */
    public void setMaterialSpecifications(String materialSpecifications) {
        this.materialSpecifications = materialSpecifications == null ? null : materialSpecifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.personnel_requirements
     *
     * @return the value of production_process_diagram_tbl.personnel_requirements
     *
     * @mbggenerated
     */
    public String getPersonnelRequirements() {
        return personnelRequirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.personnel_requirements
     *
     * @param personnelRequirements the value for production_process_diagram_tbl.personnel_requirements
     *
     * @mbggenerated
     */
    public void setPersonnelRequirements(String personnelRequirements) {
        this.personnelRequirements = personnelRequirements == null ? null : personnelRequirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.inspection_standards
     *
     * @return the value of production_process_diagram_tbl.inspection_standards
     *
     * @mbggenerated
     */
    public String getInspectionStandards() {
        return inspectionStandards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.inspection_standards
     *
     * @param inspectionStandards the value for production_process_diagram_tbl.inspection_standards
     *
     * @mbggenerated
     */
    public void setInspectionStandards(String inspectionStandards) {
        this.inspectionStandards = inspectionStandards == null ? null : inspectionStandards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.operating_rules
     *
     * @return the value of production_process_diagram_tbl.operating_rules
     *
     * @mbggenerated
     */
    public String getOperatingRules() {
        return operatingRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.operating_rules
     *
     * @param operatingRules the value for production_process_diagram_tbl.operating_rules
     *
     * @mbggenerated
     */
    public void setOperatingRules(String operatingRules) {
        this.operatingRules = operatingRules == null ? null : operatingRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.equipment
     *
     * @return the value of production_process_diagram_tbl.equipment
     *
     * @mbggenerated
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.equipment
     *
     * @param equipment the value for production_process_diagram_tbl.equipment
     *
     * @mbggenerated
     */
    public void setEquipment(String equipment) {
        this.equipment = equipment == null ? null : equipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.doc_name
     *
     * @return the value of production_process_diagram_tbl.doc_name
     *
     * @mbggenerated
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.doc_name
     *
     * @param docName the value for production_process_diagram_tbl.doc_name
     *
     * @mbggenerated
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_process_diagram_tbl.doc_url
     *
     * @return the value of production_process_diagram_tbl.doc_url
     *
     * @mbggenerated
     */
    public String getDocUrl() {
        return docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_process_diagram_tbl.doc_url
     *
     * @param docUrl the value for production_process_diagram_tbl.doc_url
     *
     * @mbggenerated
     */
    public void setDocUrl(String docUrl) {
        this.docUrl = docUrl == null ? null : docUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_process_diagram_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductionProcessDiagram other = (ProductionProcessDiagram) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getProject() == null ? other.getProject() == null : this.getProject().equals(other.getProject()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getMaterial() == null ? other.getMaterial() == null : this.getMaterial().equals(other.getMaterial()))
            && (this.getMaterialSpecifications() == null ? other.getMaterialSpecifications() == null : this.getMaterialSpecifications().equals(other.getMaterialSpecifications()))
            && (this.getPersonnelRequirements() == null ? other.getPersonnelRequirements() == null : this.getPersonnelRequirements().equals(other.getPersonnelRequirements()))
            && (this.getInspectionStandards() == null ? other.getInspectionStandards() == null : this.getInspectionStandards().equals(other.getInspectionStandards()))
            && (this.getOperatingRules() == null ? other.getOperatingRules() == null : this.getOperatingRules().equals(other.getOperatingRules()))
            && (this.getEquipment() == null ? other.getEquipment() == null : this.getEquipment().equals(other.getEquipment()))
            && (this.getDocName() == null ? other.getDocName() == null : this.getDocName().equals(other.getDocName()))
            && (this.getDocUrl() == null ? other.getDocUrl() == null : this.getDocUrl().equals(other.getDocUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_process_diagram_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getProject() == null) ? 0 : getProject().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getMaterial() == null) ? 0 : getMaterial().hashCode());
        result = prime * result + ((getMaterialSpecifications() == null) ? 0 : getMaterialSpecifications().hashCode());
        result = prime * result + ((getPersonnelRequirements() == null) ? 0 : getPersonnelRequirements().hashCode());
        result = prime * result + ((getInspectionStandards() == null) ? 0 : getInspectionStandards().hashCode());
        result = prime * result + ((getOperatingRules() == null) ? 0 : getOperatingRules().hashCode());
        result = prime * result + ((getEquipment() == null) ? 0 : getEquipment().hashCode());
        result = prime * result + ((getDocName() == null) ? 0 : getDocName().hashCode());
        result = prime * result + ((getDocUrl() == null) ? 0 : getDocUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_process_diagram_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", project=").append(project);
        sb.append(", description=").append(description);
        sb.append(", material=").append(material);
        sb.append(", materialSpecifications=").append(materialSpecifications);
        sb.append(", personnelRequirements=").append(personnelRequirements);
        sb.append(", inspectionStandards=").append(inspectionStandards);
        sb.append(", operatingRules=").append(operatingRules);
        sb.append(", equipment=").append(equipment);
        sb.append(", docName=").append(docName);
        sb.append(", docUrl=").append(docUrl);
        sb.append("]");
        return sb.toString();
    }
}