package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TAccident implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = 8493286451059654328L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.person_death
     *
     * @mbggenerated
     */
    private String personDeath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.person_miss
     *
     * @mbggenerated
     */
    private String personMiss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.person_injured
     *
     * @mbggenerated
     */
    private String personInjured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.economic_loss
     *
     * @mbggenerated
     */
    private String economicLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.doc_name
     *
     * @mbggenerated
     */
    private String docName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_accident_tbl.doc_url
     *
     * @mbggenerated
     */
    private String docUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accident_tbl
     *
     * @mbggenerated
     */
    public TAccident(Integer id, Integer userId, String department, Date time, String type, String personDeath, String personMiss, String personInjured, String economicLoss, String docName, String docUrl) {
        this.id = id;
        this.userId = userId;
        this.department = department;
        this.time = time;
        this.type = type;
        this.personDeath = personDeath;
        this.personMiss = personMiss;
        this.personInjured = personInjured;
        this.economicLoss = economicLoss;
        this.docName = docName;
        this.docUrl = docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accident_tbl
     *
     * @mbggenerated
     */
    public TAccident() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.id
     *
     * @return the value of t_accident_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.id
     *
     * @param id the value for t_accident_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.user_id
     *
     * @return the value of t_accident_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.user_id
     *
     * @param userId the value for t_accident_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.department
     *
     * @return the value of t_accident_tbl.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.department
     *
     * @param department the value for t_accident_tbl.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.time
     *
     * @return the value of t_accident_tbl.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.time
     *
     * @param time the value for t_accident_tbl.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.type
     *
     * @return the value of t_accident_tbl.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.type
     *
     * @param type the value for t_accident_tbl.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.person_death
     *
     * @return the value of t_accident_tbl.person_death
     *
     * @mbggenerated
     */
    public String getPersonDeath() {
        return personDeath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.person_death
     *
     * @param personDeath the value for t_accident_tbl.person_death
     *
     * @mbggenerated
     */
    public void setPersonDeath(String personDeath) {
        this.personDeath = personDeath == null ? null : personDeath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.person_miss
     *
     * @return the value of t_accident_tbl.person_miss
     *
     * @mbggenerated
     */
    public String getPersonMiss() {
        return personMiss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.person_miss
     *
     * @param personMiss the value for t_accident_tbl.person_miss
     *
     * @mbggenerated
     */
    public void setPersonMiss(String personMiss) {
        this.personMiss = personMiss == null ? null : personMiss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.person_injured
     *
     * @return the value of t_accident_tbl.person_injured
     *
     * @mbggenerated
     */
    public String getPersonInjured() {
        return personInjured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.person_injured
     *
     * @param personInjured the value for t_accident_tbl.person_injured
     *
     * @mbggenerated
     */
    public void setPersonInjured(String personInjured) {
        this.personInjured = personInjured == null ? null : personInjured.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.economic_loss
     *
     * @return the value of t_accident_tbl.economic_loss
     *
     * @mbggenerated
     */
    public String getEconomicLoss() {
        return economicLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.economic_loss
     *
     * @param economicLoss the value for t_accident_tbl.economic_loss
     *
     * @mbggenerated
     */
    public void setEconomicLoss(String economicLoss) {
        this.economicLoss = economicLoss == null ? null : economicLoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.doc_name
     *
     * @return the value of t_accident_tbl.doc_name
     *
     * @mbggenerated
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.doc_name
     *
     * @param docName the value for t_accident_tbl.doc_name
     *
     * @mbggenerated
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_accident_tbl.doc_url
     *
     * @return the value of t_accident_tbl.doc_url
     *
     * @mbggenerated
     */
    public String getDocUrl() {
        return docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_accident_tbl.doc_url
     *
     * @param docUrl the value for t_accident_tbl.doc_url
     *
     * @mbggenerated
     */
    public void setDocUrl(String docUrl) {
        this.docUrl = docUrl == null ? null : docUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accident_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TAccident other = (TAccident) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDepartment() == null ? other.getDepartment() == null : this.getDepartment().equals(other.getDepartment()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPersonDeath() == null ? other.getPersonDeath() == null : this.getPersonDeath().equals(other.getPersonDeath()))
            && (this.getPersonMiss() == null ? other.getPersonMiss() == null : this.getPersonMiss().equals(other.getPersonMiss()))
            && (this.getPersonInjured() == null ? other.getPersonInjured() == null : this.getPersonInjured().equals(other.getPersonInjured()))
            && (this.getEconomicLoss() == null ? other.getEconomicLoss() == null : this.getEconomicLoss().equals(other.getEconomicLoss()))
            && (this.getDocName() == null ? other.getDocName() == null : this.getDocName().equals(other.getDocName()))
            && (this.getDocUrl() == null ? other.getDocUrl() == null : this.getDocUrl().equals(other.getDocUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accident_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDepartment() == null) ? 0 : getDepartment().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPersonDeath() == null) ? 0 : getPersonDeath().hashCode());
        result = prime * result + ((getPersonMiss() == null) ? 0 : getPersonMiss().hashCode());
        result = prime * result + ((getPersonInjured() == null) ? 0 : getPersonInjured().hashCode());
        result = prime * result + ((getEconomicLoss() == null) ? 0 : getEconomicLoss().hashCode());
        result = prime * result + ((getDocName() == null) ? 0 : getDocName().hashCode());
        result = prime * result + ((getDocUrl() == null) ? 0 : getDocUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accident_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", department=").append(department);
        sb.append(", time=").append(time);
        sb.append(", type=").append(type);
        sb.append(", personDeath=").append(personDeath);
        sb.append(", personMiss=").append(personMiss);
        sb.append(", personInjured=").append(personInjured);
        sb.append(", economicLoss=").append(economicLoss);
        sb.append(", docName=").append(docName);
        sb.append(", docUrl=").append(docUrl);
        sb.append("]");
        return sb.toString();
    }
}