package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TCheck implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -4106012179160875840L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.depart
     *
     * @mbggenerated
     */
    private String depart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.depart_img
     *
     * @mbggenerated
     */
    private String departImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.industry_id
     *
     * @mbggenerated
     */
    private Integer industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.industry_type
     *
     * @mbggenerated
     */
    private Integer industryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.expect_time
     *
     * @mbggenerated
     */
    private Date expectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.real_time
     *
     * @mbggenerated
     */
    private Date realTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.cheker
     *
     * @mbggenerated
     */
    private String cheker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.dapart_contact
     *
     * @mbggenerated
     */
    private String dapartContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_tbl.check_company
     *
     * @mbggenerated
     */
    private String checkCompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_tbl
     *
     * @mbggenerated
     */
    public TCheck(Integer id, Integer flag, String title, String depart, String departImg, Integer userId, Integer createUser, Integer modelId, Integer type, Integer industryId, Integer industryType, Date expectTime, Date realTime, String cheker, String contact, String dapartContact, Integer status, Date createTime, Integer del, String checkCompany) {
        this.id = id;
        this.flag = flag;
        this.title = title;
        this.depart = depart;
        this.departImg = departImg;
        this.userId = userId;
        this.createUser = createUser;
        this.modelId = modelId;
        this.type = type;
        this.industryId = industryId;
        this.industryType = industryType;
        this.expectTime = expectTime;
        this.realTime = realTime;
        this.cheker = cheker;
        this.contact = contact;
        this.dapartContact = dapartContact;
        this.status = status;
        this.createTime = createTime;
        this.del = del;
        this.checkCompany = checkCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_tbl
     *
     * @mbggenerated
     */
    public TCheck() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.id
     *
     * @return the value of t_check_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.id
     *
     * @param id the value for t_check_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.flag
     *
     * @return the value of t_check_tbl.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.flag
     *
     * @param flag the value for t_check_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.title
     *
     * @return the value of t_check_tbl.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.title
     *
     * @param title the value for t_check_tbl.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.depart
     *
     * @return the value of t_check_tbl.depart
     *
     * @mbggenerated
     */
    public String getDepart() {
        return depart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.depart
     *
     * @param depart the value for t_check_tbl.depart
     *
     * @mbggenerated
     */
    public void setDepart(String depart) {
        this.depart = depart == null ? null : depart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.depart_img
     *
     * @return the value of t_check_tbl.depart_img
     *
     * @mbggenerated
     */
    public String getDepartImg() {
        return departImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.depart_img
     *
     * @param departImg the value for t_check_tbl.depart_img
     *
     * @mbggenerated
     */
    public void setDepartImg(String departImg) {
        this.departImg = departImg == null ? null : departImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.user_id
     *
     * @return the value of t_check_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.user_id
     *
     * @param userId the value for t_check_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.create_user
     *
     * @return the value of t_check_tbl.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.create_user
     *
     * @param createUser the value for t_check_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.model_id
     *
     * @return the value of t_check_tbl.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.model_id
     *
     * @param modelId the value for t_check_tbl.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.type
     *
     * @return the value of t_check_tbl.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.type
     *
     * @param type the value for t_check_tbl.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.industry_id
     *
     * @return the value of t_check_tbl.industry_id
     *
     * @mbggenerated
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.industry_id
     *
     * @param industryId the value for t_check_tbl.industry_id
     *
     * @mbggenerated
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.industry_type
     *
     * @return the value of t_check_tbl.industry_type
     *
     * @mbggenerated
     */
    public Integer getIndustryType() {
        return industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.industry_type
     *
     * @param industryType the value for t_check_tbl.industry_type
     *
     * @mbggenerated
     */
    public void setIndustryType(Integer industryType) {
        this.industryType = industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.expect_time
     *
     * @return the value of t_check_tbl.expect_time
     *
     * @mbggenerated
     */
    public Date getExpectTime() {
        return expectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.expect_time
     *
     * @param expectTime the value for t_check_tbl.expect_time
     *
     * @mbggenerated
     */
    public void setExpectTime(Date expectTime) {
        this.expectTime = expectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.real_time
     *
     * @return the value of t_check_tbl.real_time
     *
     * @mbggenerated
     */
    public Date getRealTime() {
        return realTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.real_time
     *
     * @param realTime the value for t_check_tbl.real_time
     *
     * @mbggenerated
     */
    public void setRealTime(Date realTime) {
        this.realTime = realTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.cheker
     *
     * @return the value of t_check_tbl.cheker
     *
     * @mbggenerated
     */
    public String getCheker() {
        return cheker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.cheker
     *
     * @param cheker the value for t_check_tbl.cheker
     *
     * @mbggenerated
     */
    public void setCheker(String cheker) {
        this.cheker = cheker == null ? null : cheker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.contact
     *
     * @return the value of t_check_tbl.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.contact
     *
     * @param contact the value for t_check_tbl.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.dapart_contact
     *
     * @return the value of t_check_tbl.dapart_contact
     *
     * @mbggenerated
     */
    public String getDapartContact() {
        return dapartContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.dapart_contact
     *
     * @param dapartContact the value for t_check_tbl.dapart_contact
     *
     * @mbggenerated
     */
    public void setDapartContact(String dapartContact) {
        this.dapartContact = dapartContact == null ? null : dapartContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.status
     *
     * @return the value of t_check_tbl.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.status
     *
     * @param status the value for t_check_tbl.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.create_time
     *
     * @return the value of t_check_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.create_time
     *
     * @param createTime the value for t_check_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.del
     *
     * @return the value of t_check_tbl.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.del
     *
     * @param del the value for t_check_tbl.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_tbl.check_company
     *
     * @return the value of t_check_tbl.check_company
     *
     * @mbggenerated
     */
    public String getCheckCompany() {
        return checkCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_tbl.check_company
     *
     * @param checkCompany the value for t_check_tbl.check_company
     *
     * @mbggenerated
     */
    public void setCheckCompany(String checkCompany) {
        this.checkCompany = checkCompany == null ? null : checkCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCheck other = (TCheck) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDepart() == null ? other.getDepart() == null : this.getDepart().equals(other.getDepart()))
            && (this.getDepartImg() == null ? other.getDepartImg() == null : this.getDepartImg().equals(other.getDepartImg()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getIndustryId() == null ? other.getIndustryId() == null : this.getIndustryId().equals(other.getIndustryId()))
            && (this.getIndustryType() == null ? other.getIndustryType() == null : this.getIndustryType().equals(other.getIndustryType()))
            && (this.getExpectTime() == null ? other.getExpectTime() == null : this.getExpectTime().equals(other.getExpectTime()))
            && (this.getRealTime() == null ? other.getRealTime() == null : this.getRealTime().equals(other.getRealTime()))
            && (this.getCheker() == null ? other.getCheker() == null : this.getCheker().equals(other.getCheker()))
            && (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getDapartContact() == null ? other.getDapartContact() == null : this.getDapartContact().equals(other.getDapartContact()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCheckCompany() == null ? other.getCheckCompany() == null : this.getCheckCompany().equals(other.getCheckCompany()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDepart() == null) ? 0 : getDepart().hashCode());
        result = prime * result + ((getDepartImg() == null) ? 0 : getDepartImg().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getIndustryId() == null) ? 0 : getIndustryId().hashCode());
        result = prime * result + ((getIndustryType() == null) ? 0 : getIndustryType().hashCode());
        result = prime * result + ((getExpectTime() == null) ? 0 : getExpectTime().hashCode());
        result = prime * result + ((getRealTime() == null) ? 0 : getRealTime().hashCode());
        result = prime * result + ((getCheker() == null) ? 0 : getCheker().hashCode());
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getDapartContact() == null) ? 0 : getDapartContact().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCheckCompany() == null) ? 0 : getCheckCompany().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flag=").append(flag);
        sb.append(", title=").append(title);
        sb.append(", depart=").append(depart);
        sb.append(", departImg=").append(departImg);
        sb.append(", userId=").append(userId);
        sb.append(", createUser=").append(createUser);
        sb.append(", modelId=").append(modelId);
        sb.append(", type=").append(type);
        sb.append(", industryId=").append(industryId);
        sb.append(", industryType=").append(industryType);
        sb.append(", expectTime=").append(expectTime);
        sb.append(", realTime=").append(realTime);
        sb.append(", cheker=").append(cheker);
        sb.append(", contact=").append(contact);
        sb.append(", dapartContact=").append(dapartContact);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", del=").append(del);
        sb.append(", checkCompany=").append(checkCompany);
        sb.append("]");
        return sb.toString();
    }
}