package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TCheckItem implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -359389609617549303L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.level_id
     *
     * @mbggenerated
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.levels
     *
     * @mbggenerated
     */
    private String levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.reference
     *
     * @mbggenerated
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.part_id
     *
     * @mbggenerated
     */
    private Integer partId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.check_id
     *
     * @mbggenerated
     */
    private Integer checkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.files
     *
     * @mbggenerated
     */
    private String files;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.suggest
     *
     * @mbggenerated
     */
    private Integer suggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.deadline
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.plan_time
     *
     * @mbggenerated
     */
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.recheck_time
     *
     * @mbggenerated
     */
    private Date recheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.recheck_file
     *
     * @mbggenerated
     */
    private String recheckFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.recheck_memo
     *
     * @mbggenerated
     */
    private String recheckMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_item_tbl
     *
     * @mbggenerated
     */
    public TCheckItem(Integer id, String content, Integer levelId, String levels, String reference, Integer partId, Integer checkId, Integer status, String memo, String files, Integer suggest, Date deadline, Date planTime, Date recheckTime, String recheckFile, String recheckMemo) {
        this.id = id;
        this.content = content;
        this.levelId = levelId;
        this.levels = levels;
        this.reference = reference;
        this.partId = partId;
        this.checkId = checkId;
        this.status = status;
        this.memo = memo;
        this.files = files;
        this.suggest = suggest;
        this.deadline = deadline;
        this.planTime = planTime;
        this.recheckTime = recheckTime;
        this.recheckFile = recheckFile;
        this.recheckMemo = recheckMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_item_tbl
     *
     * @mbggenerated
     */
    public TCheckItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.id
     *
     * @return the value of t_check_item_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.id
     *
     * @param id the value for t_check_item_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.content
     *
     * @return the value of t_check_item_tbl.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.content
     *
     * @param content the value for t_check_item_tbl.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.level_id
     *
     * @return the value of t_check_item_tbl.level_id
     *
     * @mbggenerated
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.level_id
     *
     * @param levelId the value for t_check_item_tbl.level_id
     *
     * @mbggenerated
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.levels
     *
     * @return the value of t_check_item_tbl.levels
     *
     * @mbggenerated
     */
    public String getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.levels
     *
     * @param levels the value for t_check_item_tbl.levels
     *
     * @mbggenerated
     */
    public void setLevels(String levels) {
        this.levels = levels == null ? null : levels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.reference
     *
     * @return the value of t_check_item_tbl.reference
     *
     * @mbggenerated
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.reference
     *
     * @param reference the value for t_check_item_tbl.reference
     *
     * @mbggenerated
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.part_id
     *
     * @return the value of t_check_item_tbl.part_id
     *
     * @mbggenerated
     */
    public Integer getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.part_id
     *
     * @param partId the value for t_check_item_tbl.part_id
     *
     * @mbggenerated
     */
    public void setPartId(Integer partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.check_id
     *
     * @return the value of t_check_item_tbl.check_id
     *
     * @mbggenerated
     */
    public Integer getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.check_id
     *
     * @param checkId the value for t_check_item_tbl.check_id
     *
     * @mbggenerated
     */
    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.status
     *
     * @return the value of t_check_item_tbl.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.status
     *
     * @param status the value for t_check_item_tbl.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.memo
     *
     * @return the value of t_check_item_tbl.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.memo
     *
     * @param memo the value for t_check_item_tbl.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.files
     *
     * @return the value of t_check_item_tbl.files
     *
     * @mbggenerated
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.files
     *
     * @param files the value for t_check_item_tbl.files
     *
     * @mbggenerated
     */
    public void setFiles(String files) {
        this.files = files == null ? null : files.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.suggest
     *
     * @return the value of t_check_item_tbl.suggest
     *
     * @mbggenerated
     */
    public Integer getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.suggest
     *
     * @param suggest the value for t_check_item_tbl.suggest
     *
     * @mbggenerated
     */
    public void setSuggest(Integer suggest) {
        this.suggest = suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.deadline
     *
     * @return the value of t_check_item_tbl.deadline
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.deadline
     *
     * @param deadline the value for t_check_item_tbl.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.plan_time
     *
     * @return the value of t_check_item_tbl.plan_time
     *
     * @mbggenerated
     */
    public Date getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.plan_time
     *
     * @param planTime the value for t_check_item_tbl.plan_time
     *
     * @mbggenerated
     */
    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.recheck_time
     *
     * @return the value of t_check_item_tbl.recheck_time
     *
     * @mbggenerated
     */
    public Date getRecheckTime() {
        return recheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.recheck_time
     *
     * @param recheckTime the value for t_check_item_tbl.recheck_time
     *
     * @mbggenerated
     */
    public void setRecheckTime(Date recheckTime) {
        this.recheckTime = recheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.recheck_file
     *
     * @return the value of t_check_item_tbl.recheck_file
     *
     * @mbggenerated
     */
    public String getRecheckFile() {
        return recheckFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.recheck_file
     *
     * @param recheckFile the value for t_check_item_tbl.recheck_file
     *
     * @mbggenerated
     */
    public void setRecheckFile(String recheckFile) {
        this.recheckFile = recheckFile == null ? null : recheckFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check_item_tbl.recheck_memo
     *
     * @return the value of t_check_item_tbl.recheck_memo
     *
     * @mbggenerated
     */
    public String getRecheckMemo() {
        return recheckMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check_item_tbl.recheck_memo
     *
     * @param recheckMemo the value for t_check_item_tbl.recheck_memo
     *
     * @mbggenerated
     */
    public void setRecheckMemo(String recheckMemo) {
        this.recheckMemo = recheckMemo == null ? null : recheckMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCheckItem other = (TCheckItem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getLevelId() == null ? other.getLevelId() == null : this.getLevelId().equals(other.getLevelId()))
            && (this.getLevels() == null ? other.getLevels() == null : this.getLevels().equals(other.getLevels()))
            && (this.getReference() == null ? other.getReference() == null : this.getReference().equals(other.getReference()))
            && (this.getPartId() == null ? other.getPartId() == null : this.getPartId().equals(other.getPartId()))
            && (this.getCheckId() == null ? other.getCheckId() == null : this.getCheckId().equals(other.getCheckId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getFiles() == null ? other.getFiles() == null : this.getFiles().equals(other.getFiles()))
            && (this.getSuggest() == null ? other.getSuggest() == null : this.getSuggest().equals(other.getSuggest()))
            && (this.getDeadline() == null ? other.getDeadline() == null : this.getDeadline().equals(other.getDeadline()))
            && (this.getPlanTime() == null ? other.getPlanTime() == null : this.getPlanTime().equals(other.getPlanTime()))
            && (this.getRecheckTime() == null ? other.getRecheckTime() == null : this.getRecheckTime().equals(other.getRecheckTime()))
            && (this.getRecheckFile() == null ? other.getRecheckFile() == null : this.getRecheckFile().equals(other.getRecheckFile()))
            && (this.getRecheckMemo() == null ? other.getRecheckMemo() == null : this.getRecheckMemo().equals(other.getRecheckMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getLevelId() == null) ? 0 : getLevelId().hashCode());
        result = prime * result + ((getLevels() == null) ? 0 : getLevels().hashCode());
        result = prime * result + ((getReference() == null) ? 0 : getReference().hashCode());
        result = prime * result + ((getPartId() == null) ? 0 : getPartId().hashCode());
        result = prime * result + ((getCheckId() == null) ? 0 : getCheckId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getFiles() == null) ? 0 : getFiles().hashCode());
        result = prime * result + ((getSuggest() == null) ? 0 : getSuggest().hashCode());
        result = prime * result + ((getDeadline() == null) ? 0 : getDeadline().hashCode());
        result = prime * result + ((getPlanTime() == null) ? 0 : getPlanTime().hashCode());
        result = prime * result + ((getRecheckTime() == null) ? 0 : getRecheckTime().hashCode());
        result = prime * result + ((getRecheckFile() == null) ? 0 : getRecheckFile().hashCode());
        result = prime * result + ((getRecheckMemo() == null) ? 0 : getRecheckMemo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", levelId=").append(levelId);
        sb.append(", levels=").append(levels);
        sb.append(", reference=").append(reference);
        sb.append(", partId=").append(partId);
        sb.append(", checkId=").append(checkId);
        sb.append(", status=").append(status);
        sb.append(", memo=").append(memo);
        sb.append(", files=").append(files);
        sb.append(", suggest=").append(suggest);
        sb.append(", deadline=").append(deadline);
        sb.append(", planTime=").append(planTime);
        sb.append(", recheckTime=").append(recheckTime);
        sb.append(", recheckFile=").append(recheckFile);
        sb.append(", recheckMemo=").append(recheckMemo);
        sb.append("]");
        return sb.toString();
    }
}