package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TCheckItem implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -359389609617549303L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.level_id
     *
     * @mbggenerated
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.levels
     *
     * @mbggenerated
     */
    private String levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.reference
     *
     * @mbggenerated
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.part_id
     * @mbggenerated
     */
    private Integer partId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.check_id
     *
     * @mbggenerated
     */
    private Integer checkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.files
     *
     * @mbggenerated
     */
    private String files;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.suggest
     *
     * @mbggenerated
     */
    private Integer suggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.deadline
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.plan_time
     *
     * @mbggenerated
     */
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.recheck_time
     *
     * @mbggenerated
     */
    private Date recheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.recheck_file
     *
     * @mbggenerated
     */
    private String recheckFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_item_tbl.recheck_memo
     *
     * @mbggenerated
     */
    private String recheckMemo;

    private String fileAddress;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getLevelId() {
        return levelId;
    }

    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    public String getLevels() {
        return levels;
    }

    public void setLevels(String levels) {
        this.levels = levels;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public Integer getPartId() {
        return partId;
    }

    public void setPartId(Integer partId) {
        this.partId = partId;
    }

    public Integer getCheckId() {
        return checkId;
    }

    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getFiles() {
        return files;
    }

    public void setFiles(String files) {
        this.files = files;
    }

    public Integer getSuggest() {
        return suggest;
    }

    public void setSuggest(Integer suggest) {
        this.suggest = suggest;
    }

    public Date getDeadline() {
        return deadline;
    }

    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    public Date getPlanTime() {
        return planTime;
    }

    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    public Date getRecheckTime() {
        return recheckTime;
    }

    public void setRecheckTime(Date recheckTime) {
        this.recheckTime = recheckTime;
    }

    public String getRecheckFile() {
        return recheckFile;
    }

    public void setRecheckFile(String recheckFile) {
        this.recheckFile = recheckFile;
    }

    public String getRecheckMemo() {
        return recheckMemo;
    }

    public void setRecheckMemo(String recheckMemo) {
        this.recheckMemo = recheckMemo;
    }

    public String getFileAddress() {
        return fileAddress;
    }

    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress;
    }

    public TCheckItem() {
    }

    public TCheckItem(Integer id, String content, Integer levelId, String levels, String reference, Integer partId, Integer checkId, Integer status, String memo, String files, Integer suggest, Date deadline, Date planTime, Date recheckTime, String recheckFile, String recheckMemo, String fileAddress) {
        this.id = id;
        this.content = content;
        this.levelId = levelId;
        this.levels = levels;
        this.reference = reference;
        this.partId = partId;
        this.checkId = checkId;
        this.status = status;
        this.memo = memo;
        this.files = files;
        this.suggest = suggest;
        this.deadline = deadline;
        this.planTime = planTime;
        this.recheckTime = recheckTime;
        this.recheckFile = recheckFile;
        this.recheckMemo = recheckMemo;
        this.fileAddress = fileAddress;
    }

    @Override
    public String toString() {
        return "TCheckItem{" +
                "id=" + id +
                ", content='" + content + '\'' +
                ", levelId=" + levelId +
                ", levels='" + levels + '\'' +
                ", reference='" + reference + '\'' +
                ", partId=" + partId +
                ", checkId=" + checkId +
                ", status=" + status +
                ", memo='" + memo + '\'' +
                ", files='" + files + '\'' +
                ", suggest=" + suggest +
                ", deadline=" + deadline +
                ", planTime=" + planTime +
                ", recheckTime=" + recheckTime +
                ", recheckFile='" + recheckFile + '\'' +
                ", recheckMemo='" + recheckMemo + '\'' +
                ", fileAddress='" + fileAddress + '\'' +
                '}';
    }
}