package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TDrill implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -4479805226270549466L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.drill_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date drillTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.doc_name
     *
     * @mbggenerated
     */
    private String docName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drill_tbl.doc_url
     *
     * @mbggenerated
     */
    private String docUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drill_tbl
     *
     * @mbggenerated
     */
    public TDrill(Integer id, Integer userId, String name, String content, Date drillTime, String docName, String docUrl) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.content = content;
        this.drillTime = drillTime;
        this.docName = docName;
        this.docUrl = docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drill_tbl
     *
     * @mbggenerated
     */
    public TDrill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.id
     *
     * @return the value of t_drill_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.id
     *
     * @param id the value for t_drill_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.user_id
     *
     * @return the value of t_drill_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.user_id
     *
     * @param userId the value for t_drill_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.name
     *
     * @return the value of t_drill_tbl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.name
     *
     * @param name the value for t_drill_tbl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.content
     *
     * @return the value of t_drill_tbl.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.content
     *
     * @param content the value for t_drill_tbl.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.drill_time
     *
     * @return the value of t_drill_tbl.drill_time
     *
     * @mbggenerated
     */
    public Date getDrillTime() {
        return drillTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.drill_time
     *
     * @param drillTime the value for t_drill_tbl.drill_time
     *
     * @mbggenerated
     */
    public void setDrillTime(Date drillTime) {
        this.drillTime = drillTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.doc_name
     *
     * @return the value of t_drill_tbl.doc_name
     *
     * @mbggenerated
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.doc_name
     *
     * @param docName the value for t_drill_tbl.doc_name
     *
     * @mbggenerated
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drill_tbl.doc_url
     *
     * @return the value of t_drill_tbl.doc_url
     *
     * @mbggenerated
     */
    public String getDocUrl() {
        return docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drill_tbl.doc_url
     *
     * @param docUrl the value for t_drill_tbl.doc_url
     *
     * @mbggenerated
     */
    public void setDocUrl(String docUrl) {
        this.docUrl = docUrl == null ? null : docUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drill_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TDrill other = (TDrill) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getDrillTime() == null ? other.getDrillTime() == null : this.getDrillTime().equals(other.getDrillTime()))
            && (this.getDocName() == null ? other.getDocName() == null : this.getDocName().equals(other.getDocName()))
            && (this.getDocUrl() == null ? other.getDocUrl() == null : this.getDocUrl().equals(other.getDocUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drill_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getDrillTime() == null) ? 0 : getDrillTime().hashCode());
        result = prime * result + ((getDocName() == null) ? 0 : getDocName().hashCode());
        result = prime * result + ((getDocUrl() == null) ? 0 : getDocUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drill_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", content=").append(content);
        sb.append(", drillTime=").append(drillTime);
        sb.append(", docName=").append(docName);
        sb.append(", docUrl=").append(docUrl);
        sb.append("]");
        return sb.toString();
    }
}