package com.spring.web.model;

import java.io.Serializable;

public class TItem implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = 4621868838381938258L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_tbl.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_tbl.level_id
     *
     * @mbggenerated
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_tbl.reference
     *
     * @mbggenerated
     */
    private String reference;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    public TItem(Integer id, String content, Integer levelId, String reference) {
        this.id = id;
        this.content = content;
        this.levelId = levelId;
        this.reference = reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    public TItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_tbl.id
     *
     * @return the value of t_item_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_tbl.id
     *
     * @param id the value for t_item_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_tbl.content
     *
     * @return the value of t_item_tbl.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_tbl.content
     *
     * @param content the value for t_item_tbl.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_tbl.level_id
     *
     * @return the value of t_item_tbl.level_id
     *
     * @mbggenerated
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_tbl.level_id
     *
     * @param levelId the value for t_item_tbl.level_id
     *
     * @mbggenerated
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_tbl.reference
     *
     * @return the value of t_item_tbl.reference
     *
     * @mbggenerated
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_tbl.reference
     *
     * @param reference the value for t_item_tbl.reference
     *
     * @mbggenerated
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TItem other = (TItem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getLevelId() == null ? other.getLevelId() == null : this.getLevelId().equals(other.getLevelId()))
            && (this.getReference() == null ? other.getReference() == null : this.getReference().equals(other.getReference()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getLevelId() == null) ? 0 : getLevelId().hashCode());
        result = prime * result + ((getReference() == null) ? 0 : getReference().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", levelId=").append(levelId);
        sb.append(", reference=").append(reference);
        sb.append("]");
        return sb.toString();
    }
}