package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TModel implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -3041972457499265513L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.part
     *
     * @mbggenerated
     */
    private String part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.industry_id
     *
     * @mbggenerated
     */
    private Integer industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.industry_type
     *
     * @mbggenerated
     */
    private Integer industryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.cycle
     *
     * @mbggenerated
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.next_check_time
     *
     * @mbggenerated
     */
    private Date nextCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.open
     *
     * @mbggenerated
     */
    private Integer open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.use_time
     *
     * @mbggenerated
     */
    private Date useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getPart() {
        return part;
    }

    public void setPart(String part) {
        this.part = part;
    }

    public Integer getIndustryId() {
        return industryId;
    }

    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    public Integer getIndustryType() {
        return industryType;
    }

    public void setIndustryType(Integer industryType) {
        this.industryType = industryType;
    }

    public Integer getCycle() {
        return cycle;
    }

    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    public Date getNextTime() {
        return nextTime;
    }

    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    public Date getNextCheckTime() {
        return nextCheckTime;
    }

    public void setNextCheckTime(Date nextCheckTime) {
        this.nextCheckTime = nextCheckTime;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getDel() {
        return del;
    }

    public void setDel(Integer del) {
        this.del = del;
    }

    public Integer getOpen() {
        return open;
    }

    public void setOpen(Integer open) {
        this.open = open;
    }

    public Date getUseTime() {
        return useTime;
    }

    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public TModel(Integer id, String title, Integer userId, Integer flag, Integer type, String part, Integer industryId, Integer industryType, Integer cycle, Date nextTime, Date nextCheckTime, String memo, Integer del, Integer open, Date useTime, Date createTime) {
        this.id = id;
        this.title = title;
        this.userId = userId;
        this.flag = flag;
        this.type = type;
        this.part = part;
        this.industryId = industryId;
        this.industryType = industryType;
        this.cycle = cycle;
        this.nextTime = nextTime;
        this.nextCheckTime = nextCheckTime;
        this.memo = memo;
        this.del = del;
        this.open = open;
        this.useTime = useTime;
        this.createTime = createTime;
    }

    public TModel() {
    }

    @Override
    public String toString() {
        return "TModel{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", userId=" + userId +
                ", flag=" + flag +
                ", type=" + type +
                ", part='" + part + '\'' +
                ", industryId=" + industryId +
                ", industryType=" + industryType +
                ", cycle=" + cycle +
                ", nextTime=" + nextTime +
                ", nextCheckTime=" + nextCheckTime +
                ", memo='" + memo + '\'' +
                ", del=" + del +
                ", open=" + open +
                ", useTime=" + useTime +
                ", createTime=" + createTime +
                '}';
    }
}