package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TModel implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -3041972457499265513L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.part
     *
     * @mbggenerated
     */
    private String part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.industry_id
     *
     * @mbggenerated
     */
    private Integer industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.industry_type
     *
     * @mbggenerated
     */
    private Integer industryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.cycle
     *
     * @mbggenerated
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.next_check_time
     *
     * @mbggenerated
     */
    private Date nextCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.open
     *
     * @mbggenerated
     */
    private Integer open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.use_time
     *
     * @mbggenerated
     */
    private Date useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    public TModel(Integer id, String title, Integer userId, Integer flag, Integer type, String part, Integer industryId, Integer industryType, Integer cycle, Date nextTime, Date nextCheckTime, String memo, Integer del, Integer open, Date useTime, Date createTime) {
        this.id = id;
        this.title = title;
        this.userId = userId;
        this.flag = flag;
        this.type = type;
        this.part = part;
        this.industryId = industryId;
        this.industryType = industryType;
        this.cycle = cycle;
        this.nextTime = nextTime;
        this.nextCheckTime = nextCheckTime;
        this.memo = memo;
        this.del = del;
        this.open = open;
        this.useTime = useTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    public TModel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.id
     *
     * @return the value of t_model_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.id
     *
     * @param id the value for t_model_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.title
     *
     * @return the value of t_model_tbl.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.title
     *
     * @param title the value for t_model_tbl.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.user_id
     *
     * @return the value of t_model_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.user_id
     *
     * @param userId the value for t_model_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.flag
     *
     * @return the value of t_model_tbl.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.flag
     *
     * @param flag the value for t_model_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.type
     *
     * @return the value of t_model_tbl.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.type
     *
     * @param type the value for t_model_tbl.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.part
     *
     * @return the value of t_model_tbl.part
     *
     * @mbggenerated
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.part
     *
     * @param part the value for t_model_tbl.part
     *
     * @mbggenerated
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.industry_id
     *
     * @return the value of t_model_tbl.industry_id
     *
     * @mbggenerated
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.industry_id
     *
     * @param industryId the value for t_model_tbl.industry_id
     *
     * @mbggenerated
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.industry_type
     *
     * @return the value of t_model_tbl.industry_type
     *
     * @mbggenerated
     */
    public Integer getIndustryType() {
        return industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.industry_type
     *
     * @param industryType the value for t_model_tbl.industry_type
     *
     * @mbggenerated
     */
    public void setIndustryType(Integer industryType) {
        this.industryType = industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.cycle
     *
     * @return the value of t_model_tbl.cycle
     *
     * @mbggenerated
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.cycle
     *
     * @param cycle the value for t_model_tbl.cycle
     *
     * @mbggenerated
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.next_time
     *
     * @return the value of t_model_tbl.next_time
     *
     * @mbggenerated
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.next_time
     *
     * @param nextTime the value for t_model_tbl.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.next_check_time
     *
     * @return the value of t_model_tbl.next_check_time
     *
     * @mbggenerated
     */
    public Date getNextCheckTime() {
        return nextCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.next_check_time
     *
     * @param nextCheckTime the value for t_model_tbl.next_check_time
     *
     * @mbggenerated
     */
    public void setNextCheckTime(Date nextCheckTime) {
        this.nextCheckTime = nextCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.memo
     *
     * @return the value of t_model_tbl.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.memo
     *
     * @param memo the value for t_model_tbl.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.del
     *
     * @return the value of t_model_tbl.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.del
     *
     * @param del the value for t_model_tbl.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.open
     *
     * @return the value of t_model_tbl.open
     *
     * @mbggenerated
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.open
     *
     * @param open the value for t_model_tbl.open
     *
     * @mbggenerated
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.use_time
     *
     * @return the value of t_model_tbl.use_time
     *
     * @mbggenerated
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.use_time
     *
     * @param useTime the value for t_model_tbl.use_time
     *
     * @mbggenerated
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_tbl.create_time
     *
     * @return the value of t_model_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_tbl.create_time
     *
     * @param createTime the value for t_model_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TModel other = (TModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPart() == null ? other.getPart() == null : this.getPart().equals(other.getPart()))
            && (this.getIndustryId() == null ? other.getIndustryId() == null : this.getIndustryId().equals(other.getIndustryId()))
            && (this.getIndustryType() == null ? other.getIndustryType() == null : this.getIndustryType().equals(other.getIndustryType()))
            && (this.getCycle() == null ? other.getCycle() == null : this.getCycle().equals(other.getCycle()))
            && (this.getNextTime() == null ? other.getNextTime() == null : this.getNextTime().equals(other.getNextTime()))
            && (this.getNextCheckTime() == null ? other.getNextCheckTime() == null : this.getNextCheckTime().equals(other.getNextCheckTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getOpen() == null ? other.getOpen() == null : this.getOpen().equals(other.getOpen()))
            && (this.getUseTime() == null ? other.getUseTime() == null : this.getUseTime().equals(other.getUseTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPart() == null) ? 0 : getPart().hashCode());
        result = prime * result + ((getIndustryId() == null) ? 0 : getIndustryId().hashCode());
        result = prime * result + ((getIndustryType() == null) ? 0 : getIndustryType().hashCode());
        result = prime * result + ((getCycle() == null) ? 0 : getCycle().hashCode());
        result = prime * result + ((getNextTime() == null) ? 0 : getNextTime().hashCode());
        result = prime * result + ((getNextCheckTime() == null) ? 0 : getNextCheckTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getOpen() == null) ? 0 : getOpen().hashCode());
        result = prime * result + ((getUseTime() == null) ? 0 : getUseTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", userId=").append(userId);
        sb.append(", flag=").append(flag);
        sb.append(", type=").append(type);
        sb.append(", part=").append(part);
        sb.append(", industryId=").append(industryId);
        sb.append(", industryType=").append(industryType);
        sb.append(", cycle=").append(cycle);
        sb.append(", nextTime=").append(nextTime);
        sb.append(", nextCheckTime=").append(nextCheckTime);
        sb.append(", memo=").append(memo);
        sb.append(", del=").append(del);
        sb.append(", open=").append(open);
        sb.append(", useTime=").append(useTime);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}