package com.spring.web.model;

import java.io.Serializable;

public class TModelPart implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -8317723257803707106L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_part_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_part_tbl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_part_tbl.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_model_part_tbl.levels
     *
     * @mbggenerated
     */
    private String levels;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_part_tbl
     *
     * @mbggenerated
     */
    public TModelPart(Integer id, String name, Integer modelId, String levels) {
        this.id = id;
        this.name = name;
        this.modelId = modelId;
        this.levels = levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_part_tbl
     *
     * @mbggenerated
     */
    public TModelPart() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_part_tbl.id
     *
     * @return the value of t_model_part_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_part_tbl.id
     *
     * @param id the value for t_model_part_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_part_tbl.name
     *
     * @return the value of t_model_part_tbl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_part_tbl.name
     *
     * @param name the value for t_model_part_tbl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_part_tbl.model_id
     *
     * @return the value of t_model_part_tbl.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_part_tbl.model_id
     *
     * @param modelId the value for t_model_part_tbl.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_model_part_tbl.levels
     *
     * @return the value of t_model_part_tbl.levels
     *
     * @mbggenerated
     */
    public String getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_model_part_tbl.levels
     *
     * @param levels the value for t_model_part_tbl.levels
     *
     * @mbggenerated
     */
    public void setLevels(String levels) {
        this.levels = levels == null ? null : levels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_part_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TModelPart other = (TModelPart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getLevels() == null ? other.getLevels() == null : this.getLevels().equals(other.getLevels()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_part_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getLevels() == null) ? 0 : getLevels().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_model_part_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", modelId=").append(modelId);
        sb.append(", levels=").append(levels);
        sb.append("]");
        return sb.toString();
    }
}