package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TRecheck implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -5938611838670223712L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.check_id
     *
     * @mbggenerated
     */
    private Integer checkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.checker
     *
     * @mbggenerated
     */
    private String checker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.check_company
     *
     * @mbggenerated
     */
    private String checkCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_tbl.dapart_contact
     *
     * @mbggenerated
     */
    private String dapartContact;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_tbl
     *
     * @mbggenerated
     */
    public TRecheck(Integer id, Integer checkId, Integer userId, Integer createUser, Integer status, Date createTime, Date nextTime, String checker, String checkCompany, String dapartContact) {
        this.id = id;
        this.checkId = checkId;
        this.userId = userId;
        this.createUser = createUser;
        this.status = status;
        this.createTime = createTime;
        this.nextTime = nextTime;
        this.checker = checker;
        this.checkCompany = checkCompany;
        this.dapartContact = dapartContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_tbl
     *
     * @mbggenerated
     */
    public TRecheck() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.id
     *
     * @return the value of t_recheck_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.id
     *
     * @param id the value for t_recheck_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.check_id
     *
     * @return the value of t_recheck_tbl.check_id
     *
     * @mbggenerated
     */
    public Integer getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.check_id
     *
     * @param checkId the value for t_recheck_tbl.check_id
     *
     * @mbggenerated
     */
    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.user_id
     *
     * @return the value of t_recheck_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.user_id
     *
     * @param userId the value for t_recheck_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.create_user
     *
     * @return the value of t_recheck_tbl.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.create_user
     *
     * @param createUser the value for t_recheck_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.status
     *
     * @return the value of t_recheck_tbl.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.status
     *
     * @param status the value for t_recheck_tbl.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.create_time
     *
     * @return the value of t_recheck_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.create_time
     *
     * @param createTime the value for t_recheck_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.next_time
     *
     * @return the value of t_recheck_tbl.next_time
     *
     * @mbggenerated
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.next_time
     *
     * @param nextTime the value for t_recheck_tbl.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.checker
     *
     * @return the value of t_recheck_tbl.checker
     *
     * @mbggenerated
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.checker
     *
     * @param checker the value for t_recheck_tbl.checker
     *
     * @mbggenerated
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.check_company
     *
     * @return the value of t_recheck_tbl.check_company
     *
     * @mbggenerated
     */
    public String getCheckCompany() {
        return checkCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.check_company
     *
     * @param checkCompany the value for t_recheck_tbl.check_company
     *
     * @mbggenerated
     */
    public void setCheckCompany(String checkCompany) {
        this.checkCompany = checkCompany == null ? null : checkCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_tbl.dapart_contact
     *
     * @return the value of t_recheck_tbl.dapart_contact
     *
     * @mbggenerated
     */
    public String getDapartContact() {
        return dapartContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_tbl.dapart_contact
     *
     * @param dapartContact the value for t_recheck_tbl.dapart_contact
     *
     * @mbggenerated
     */
    public void setDapartContact(String dapartContact) {
        this.dapartContact = dapartContact == null ? null : dapartContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TRecheck other = (TRecheck) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCheckId() == null ? other.getCheckId() == null : this.getCheckId().equals(other.getCheckId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getNextTime() == null ? other.getNextTime() == null : this.getNextTime().equals(other.getNextTime()))
            && (this.getChecker() == null ? other.getChecker() == null : this.getChecker().equals(other.getChecker()))
            && (this.getCheckCompany() == null ? other.getCheckCompany() == null : this.getCheckCompany().equals(other.getCheckCompany()))
            && (this.getDapartContact() == null ? other.getDapartContact() == null : this.getDapartContact().equals(other.getDapartContact()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCheckId() == null) ? 0 : getCheckId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getNextTime() == null) ? 0 : getNextTime().hashCode());
        result = prime * result + ((getChecker() == null) ? 0 : getChecker().hashCode());
        result = prime * result + ((getCheckCompany() == null) ? 0 : getCheckCompany().hashCode());
        result = prime * result + ((getDapartContact() == null) ? 0 : getDapartContact().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", checkId=").append(checkId);
        sb.append(", userId=").append(userId);
        sb.append(", createUser=").append(createUser);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", nextTime=").append(nextTime);
        sb.append(", checker=").append(checker);
        sb.append(", checkCompany=").append(checkCompany);
        sb.append(", dapartContact=").append(dapartContact);
        sb.append("]");
        return sb.toString();
    }
}