package com.spring.web.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class TRectification implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -2898370143950873026L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.check_id
     *
     * @mbggenerated
     */
    private Integer checkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.item1
     *
     * @mbggenerated
     */
    private String item1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.item2
     *
     * @mbggenerated
     */
    private String item2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.item3
     *
     * @mbggenerated
     */
    private String item3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.deadline
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.plan_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rectification_tbl.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rectification_tbl
     *
     * @mbggenerated
     */
    public TRectification(Integer id, Integer checkId, String item1, String item2, String item3, Date deadline, Date planTime, Integer userId, Integer createUser, Date createTime, Integer del) {
        this.id = id;
        this.checkId = checkId;
        this.item1 = item1;
        this.item2 = item2;
        this.item3 = item3;
        this.deadline = deadline;
        this.planTime = planTime;
        this.userId = userId;
        this.createUser = createUser;
        this.createTime = createTime;
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rectification_tbl
     *
     * @mbggenerated
     */
    public TRectification() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.id
     *
     * @return the value of t_rectification_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.id
     *
     * @param id the value for t_rectification_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.check_id
     *
     * @return the value of t_rectification_tbl.check_id
     *
     * @mbggenerated
     */
    public Integer getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.check_id
     *
     * @param checkId the value for t_rectification_tbl.check_id
     *
     * @mbggenerated
     */
    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.item1
     *
     * @return the value of t_rectification_tbl.item1
     *
     * @mbggenerated
     */
    public String getItem1() {
        return item1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.item1
     *
     * @param item1 the value for t_rectification_tbl.item1
     *
     * @mbggenerated
     */
    public void setItem1(String item1) {
        this.item1 = item1 == null ? null : item1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.item2
     *
     * @return the value of t_rectification_tbl.item2
     *
     * @mbggenerated
     */
    public String getItem2() {
        return item2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.item2
     *
     * @param item2 the value for t_rectification_tbl.item2
     *
     * @mbggenerated
     */
    public void setItem2(String item2) {
        this.item2 = item2 == null ? null : item2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.item3
     *
     * @return the value of t_rectification_tbl.item3
     *
     * @mbggenerated
     */
    public String getItem3() {
        return item3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.item3
     *
     * @param item3 the value for t_rectification_tbl.item3
     *
     * @mbggenerated
     */
    public void setItem3(String item3) {
        this.item3 = item3 == null ? null : item3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.deadline
     *
     * @return the value of t_rectification_tbl.deadline
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.deadline
     *
     * @param deadline the value for t_rectification_tbl.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.plan_time
     *
     * @return the value of t_rectification_tbl.plan_time
     *
     * @mbggenerated
     */
    public Date getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.plan_time
     *
     * @param planTime the value for t_rectification_tbl.plan_time
     *
     * @mbggenerated
     */
    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.user_id
     *
     * @return the value of t_rectification_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.user_id
     *
     * @param userId the value for t_rectification_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.create_user
     *
     * @return the value of t_rectification_tbl.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.create_user
     *
     * @param createUser the value for t_rectification_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.create_time
     *
     * @return the value of t_rectification_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.create_time
     *
     * @param createTime the value for t_rectification_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rectification_tbl.del
     *
     * @return the value of t_rectification_tbl.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rectification_tbl.del
     *
     * @param del the value for t_rectification_tbl.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rectification_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TRectification other = (TRectification) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCheckId() == null ? other.getCheckId() == null : this.getCheckId().equals(other.getCheckId()))
            && (this.getItem1() == null ? other.getItem1() == null : this.getItem1().equals(other.getItem1()))
            && (this.getItem2() == null ? other.getItem2() == null : this.getItem2().equals(other.getItem2()))
            && (this.getItem3() == null ? other.getItem3() == null : this.getItem3().equals(other.getItem3()))
            && (this.getDeadline() == null ? other.getDeadline() == null : this.getDeadline().equals(other.getDeadline()))
            && (this.getPlanTime() == null ? other.getPlanTime() == null : this.getPlanTime().equals(other.getPlanTime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rectification_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCheckId() == null) ? 0 : getCheckId().hashCode());
        result = prime * result + ((getItem1() == null) ? 0 : getItem1().hashCode());
        result = prime * result + ((getItem2() == null) ? 0 : getItem2().hashCode());
        result = prime * result + ((getItem3() == null) ? 0 : getItem3().hashCode());
        result = prime * result + ((getDeadline() == null) ? 0 : getDeadline().hashCode());
        result = prime * result + ((getPlanTime() == null) ? 0 : getPlanTime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rectification_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", checkId=").append(checkId);
        sb.append(", item1=").append(item1);
        sb.append(", item2=").append(item2);
        sb.append(", item3=").append(item3);
        sb.append(", deadline=").append(deadline);
        sb.append(", planTime=").append(planTime);
        sb.append(", userId=").append(userId);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", del=").append(del);
        sb.append("]");
        return sb.toString();
    }
}