package com.spring.web.model;

import java.io.Serializable;
import java.util.Date;

public class TRecheckItem implements Serializable {
    /** 
    * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
    */ 
    
    private static final long serialVersionUID = -2253453384569652932L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.recheck_id
     *
     * @mbggenerated
     */
    private Integer recheckId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.check_item_id
     *
     * @mbggenerated
     */
    private Integer checkItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.file
     *
     * @mbggenerated
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recheck_item_tbl.deadline
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    public TRecheckItem(Integer id, Integer recheckId, Integer checkItemId, Integer status, String file, String memo, Date deadline) {
        this.id = id;
        this.recheckId = recheckId;
        this.checkItemId = checkItemId;
        this.status = status;
        this.file = file;
        this.memo = memo;
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    public TRecheckItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.id
     *
     * @return the value of t_recheck_item_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.id
     *
     * @param id the value for t_recheck_item_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.recheck_id
     *
     * @return the value of t_recheck_item_tbl.recheck_id
     *
     * @mbggenerated
     */
    public Integer getRecheckId() {
        return recheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.recheck_id
     *
     * @param recheckId the value for t_recheck_item_tbl.recheck_id
     *
     * @mbggenerated
     */
    public void setRecheckId(Integer recheckId) {
        this.recheckId = recheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.check_item_id
     *
     * @return the value of t_recheck_item_tbl.check_item_id
     *
     * @mbggenerated
     */
    public Integer getCheckItemId() {
        return checkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.check_item_id
     *
     * @param checkItemId the value for t_recheck_item_tbl.check_item_id
     *
     * @mbggenerated
     */
    public void setCheckItemId(Integer checkItemId) {
        this.checkItemId = checkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.status
     *
     * @return the value of t_recheck_item_tbl.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.status
     *
     * @param status the value for t_recheck_item_tbl.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.file
     *
     * @return the value of t_recheck_item_tbl.file
     *
     * @mbggenerated
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.file
     *
     * @param file the value for t_recheck_item_tbl.file
     *
     * @mbggenerated
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.memo
     *
     * @return the value of t_recheck_item_tbl.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.memo
     *
     * @param memo the value for t_recheck_item_tbl.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recheck_item_tbl.deadline
     *
     * @return the value of t_recheck_item_tbl.deadline
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recheck_item_tbl.deadline
     *
     * @param deadline the value for t_recheck_item_tbl.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TRecheckItem other = (TRecheckItem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRecheckId() == null ? other.getRecheckId() == null : this.getRecheckId().equals(other.getRecheckId()))
            && (this.getCheckItemId() == null ? other.getCheckItemId() == null : this.getCheckItemId().equals(other.getCheckItemId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getFile() == null ? other.getFile() == null : this.getFile().equals(other.getFile()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getDeadline() == null ? other.getDeadline() == null : this.getDeadline().equals(other.getDeadline()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRecheckId() == null) ? 0 : getRecheckId().hashCode());
        result = prime * result + ((getCheckItemId() == null) ? 0 : getCheckItemId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getFile() == null) ? 0 : getFile().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getDeadline() == null) ? 0 : getDeadline().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recheck_item_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", recheckId=").append(recheckId);
        sb.append(", checkItemId=").append(checkItemId);
        sb.append(", status=").append(status);
        sb.append(", file=").append(file);
        sb.append(", memo=").append(memo);
        sb.append(", deadline=").append(deadline);
        sb.append("]");
        return sb.toString();
    }
}