package com.spring.web.model;

import java.util.Date;

public class YzLiquidAmmonia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs1
     *
     * @mbggenerated
     */
    private String aqcs1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs2
     *
     * @mbggenerated
     */
    private String aqcs2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs3
     *
     * @mbggenerated
     */
    private String aqcs3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs4
     *
     * @mbggenerated
     */
    private String aqcs4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs5
     *
     * @mbggenerated
     */
    private String aqcs5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs6
     *
     * @mbggenerated
     */
    private String aqcs6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs7
     *
     * @mbggenerated
     */
    private String aqcs7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs8
     *
     * @mbggenerated
     */
    private String aqcs8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.aqcs9
     *
     * @mbggenerated
     */
    private String aqcs9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs1
     *
     * @mbggenerated
     */
    private String zycs1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs2
     *
     * @mbggenerated
     */
    private String zycs2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs3
     *
     * @mbggenerated
     */
    private String zycs3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs4
     *
     * @mbggenerated
     */
    private String zycs4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs5
     *
     * @mbggenerated
     */
    private String zycs5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs6
     *
     * @mbggenerated
     */
    private String zycs6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs7
     *
     * @mbggenerated
     */
    private String zycs7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs8
     *
     * @mbggenerated
     */
    private String zycs8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.zycs9
     *
     * @mbggenerated
     */
    private String zycs9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.jcry
     *
     * @mbggenerated
     */
    private String jcry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_liquidammonia_permit_t.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    public YzLiquidAmmonia(Integer id, Integer uid, String aqcs1, String aqcs2, String aqcs3, String aqcs4, String aqcs5, String aqcs6, String aqcs7, String aqcs8, String aqcs9, String zycs1, String zycs2, String zycs3, String zycs4, String zycs5, String zycs6, String zycs7, String zycs8, String zycs9, String jcry, Integer del, Date ctime) {
        this.id = id;
        this.uid = uid;
        this.aqcs1 = aqcs1;
        this.aqcs2 = aqcs2;
        this.aqcs3 = aqcs3;
        this.aqcs4 = aqcs4;
        this.aqcs5 = aqcs5;
        this.aqcs6 = aqcs6;
        this.aqcs7 = aqcs7;
        this.aqcs8 = aqcs8;
        this.aqcs9 = aqcs9;
        this.zycs1 = zycs1;
        this.zycs2 = zycs2;
        this.zycs3 = zycs3;
        this.zycs4 = zycs4;
        this.zycs5 = zycs5;
        this.zycs6 = zycs6;
        this.zycs7 = zycs7;
        this.zycs8 = zycs8;
        this.zycs9 = zycs9;
        this.jcry = jcry;
        this.del = del;
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    public YzLiquidAmmonia() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.id
     *
     * @return the value of yz_liquidammonia_permit_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.id
     *
     * @param id the value for yz_liquidammonia_permit_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.uid
     *
     * @return the value of yz_liquidammonia_permit_t.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.uid
     *
     * @param uid the value for yz_liquidammonia_permit_t.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs1
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs1
     *
     * @mbggenerated
     */
    public String getAqcs1() {
        return aqcs1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs1
     *
     * @param aqcs1 the value for yz_liquidammonia_permit_t.aqcs1
     *
     * @mbggenerated
     */
    public void setAqcs1(String aqcs1) {
        this.aqcs1 = aqcs1 == null ? null : aqcs1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs2
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs2
     *
     * @mbggenerated
     */
    public String getAqcs2() {
        return aqcs2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs2
     *
     * @param aqcs2 the value for yz_liquidammonia_permit_t.aqcs2
     *
     * @mbggenerated
     */
    public void setAqcs2(String aqcs2) {
        this.aqcs2 = aqcs2 == null ? null : aqcs2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs3
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs3
     *
     * @mbggenerated
     */
    public String getAqcs3() {
        return aqcs3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs3
     *
     * @param aqcs3 the value for yz_liquidammonia_permit_t.aqcs3
     *
     * @mbggenerated
     */
    public void setAqcs3(String aqcs3) {
        this.aqcs3 = aqcs3 == null ? null : aqcs3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs4
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs4
     *
     * @mbggenerated
     */
    public String getAqcs4() {
        return aqcs4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs4
     *
     * @param aqcs4 the value for yz_liquidammonia_permit_t.aqcs4
     *
     * @mbggenerated
     */
    public void setAqcs4(String aqcs4) {
        this.aqcs4 = aqcs4 == null ? null : aqcs4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs5
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs5
     *
     * @mbggenerated
     */
    public String getAqcs5() {
        return aqcs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs5
     *
     * @param aqcs5 the value for yz_liquidammonia_permit_t.aqcs5
     *
     * @mbggenerated
     */
    public void setAqcs5(String aqcs5) {
        this.aqcs5 = aqcs5 == null ? null : aqcs5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs6
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs6
     *
     * @mbggenerated
     */
    public String getAqcs6() {
        return aqcs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs6
     *
     * @param aqcs6 the value for yz_liquidammonia_permit_t.aqcs6
     *
     * @mbggenerated
     */
    public void setAqcs6(String aqcs6) {
        this.aqcs6 = aqcs6 == null ? null : aqcs6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs7
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs7
     *
     * @mbggenerated
     */
    public String getAqcs7() {
        return aqcs7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs7
     *
     * @param aqcs7 the value for yz_liquidammonia_permit_t.aqcs7
     *
     * @mbggenerated
     */
    public void setAqcs7(String aqcs7) {
        this.aqcs7 = aqcs7 == null ? null : aqcs7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs8
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs8
     *
     * @mbggenerated
     */
    public String getAqcs8() {
        return aqcs8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs8
     *
     * @param aqcs8 the value for yz_liquidammonia_permit_t.aqcs8
     *
     * @mbggenerated
     */
    public void setAqcs8(String aqcs8) {
        this.aqcs8 = aqcs8 == null ? null : aqcs8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.aqcs9
     *
     * @return the value of yz_liquidammonia_permit_t.aqcs9
     *
     * @mbggenerated
     */
    public String getAqcs9() {
        return aqcs9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.aqcs9
     *
     * @param aqcs9 the value for yz_liquidammonia_permit_t.aqcs9
     *
     * @mbggenerated
     */
    public void setAqcs9(String aqcs9) {
        this.aqcs9 = aqcs9 == null ? null : aqcs9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs1
     *
     * @return the value of yz_liquidammonia_permit_t.zycs1
     *
     * @mbggenerated
     */
    public String getZycs1() {
        return zycs1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs1
     *
     * @param zycs1 the value for yz_liquidammonia_permit_t.zycs1
     *
     * @mbggenerated
     */
    public void setZycs1(String zycs1) {
        this.zycs1 = zycs1 == null ? null : zycs1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs2
     *
     * @return the value of yz_liquidammonia_permit_t.zycs2
     *
     * @mbggenerated
     */
    public String getZycs2() {
        return zycs2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs2
     *
     * @param zycs2 the value for yz_liquidammonia_permit_t.zycs2
     *
     * @mbggenerated
     */
    public void setZycs2(String zycs2) {
        this.zycs2 = zycs2 == null ? null : zycs2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs3
     *
     * @return the value of yz_liquidammonia_permit_t.zycs3
     *
     * @mbggenerated
     */
    public String getZycs3() {
        return zycs3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs3
     *
     * @param zycs3 the value for yz_liquidammonia_permit_t.zycs3
     *
     * @mbggenerated
     */
    public void setZycs3(String zycs3) {
        this.zycs3 = zycs3 == null ? null : zycs3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs4
     *
     * @return the value of yz_liquidammonia_permit_t.zycs4
     *
     * @mbggenerated
     */
    public String getZycs4() {
        return zycs4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs4
     *
     * @param zycs4 the value for yz_liquidammonia_permit_t.zycs4
     *
     * @mbggenerated
     */
    public void setZycs4(String zycs4) {
        this.zycs4 = zycs4 == null ? null : zycs4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs5
     *
     * @return the value of yz_liquidammonia_permit_t.zycs5
     *
     * @mbggenerated
     */
    public String getZycs5() {
        return zycs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs5
     *
     * @param zycs5 the value for yz_liquidammonia_permit_t.zycs5
     *
     * @mbggenerated
     */
    public void setZycs5(String zycs5) {
        this.zycs5 = zycs5 == null ? null : zycs5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs6
     *
     * @return the value of yz_liquidammonia_permit_t.zycs6
     *
     * @mbggenerated
     */
    public String getZycs6() {
        return zycs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs6
     *
     * @param zycs6 the value for yz_liquidammonia_permit_t.zycs6
     *
     * @mbggenerated
     */
    public void setZycs6(String zycs6) {
        this.zycs6 = zycs6 == null ? null : zycs6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs7
     *
     * @return the value of yz_liquidammonia_permit_t.zycs7
     *
     * @mbggenerated
     */
    public String getZycs7() {
        return zycs7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs7
     *
     * @param zycs7 the value for yz_liquidammonia_permit_t.zycs7
     *
     * @mbggenerated
     */
    public void setZycs7(String zycs7) {
        this.zycs7 = zycs7 == null ? null : zycs7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs8
     *
     * @return the value of yz_liquidammonia_permit_t.zycs8
     *
     * @mbggenerated
     */
    public String getZycs8() {
        return zycs8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs8
     *
     * @param zycs8 the value for yz_liquidammonia_permit_t.zycs8
     *
     * @mbggenerated
     */
    public void setZycs8(String zycs8) {
        this.zycs8 = zycs8 == null ? null : zycs8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.zycs9
     *
     * @return the value of yz_liquidammonia_permit_t.zycs9
     *
     * @mbggenerated
     */
    public String getZycs9() {
        return zycs9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.zycs9
     *
     * @param zycs9 the value for yz_liquidammonia_permit_t.zycs9
     *
     * @mbggenerated
     */
    public void setZycs9(String zycs9) {
        this.zycs9 = zycs9 == null ? null : zycs9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.jcry
     *
     * @return the value of yz_liquidammonia_permit_t.jcry
     *
     * @mbggenerated
     */
    public String getJcry() {
        return jcry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.jcry
     *
     * @param jcry the value for yz_liquidammonia_permit_t.jcry
     *
     * @mbggenerated
     */
    public void setJcry(String jcry) {
        this.jcry = jcry == null ? null : jcry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.del
     *
     * @return the value of yz_liquidammonia_permit_t.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.del
     *
     * @param del the value for yz_liquidammonia_permit_t.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_liquidammonia_permit_t.ctime
     *
     * @return the value of yz_liquidammonia_permit_t.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_liquidammonia_permit_t.ctime
     *
     * @param ctime the value for yz_liquidammonia_permit_t.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YzLiquidAmmonia other = (YzLiquidAmmonia) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getAqcs1() == null ? other.getAqcs1() == null : this.getAqcs1().equals(other.getAqcs1()))
            && (this.getAqcs2() == null ? other.getAqcs2() == null : this.getAqcs2().equals(other.getAqcs2()))
            && (this.getAqcs3() == null ? other.getAqcs3() == null : this.getAqcs3().equals(other.getAqcs3()))
            && (this.getAqcs4() == null ? other.getAqcs4() == null : this.getAqcs4().equals(other.getAqcs4()))
            && (this.getAqcs5() == null ? other.getAqcs5() == null : this.getAqcs5().equals(other.getAqcs5()))
            && (this.getAqcs6() == null ? other.getAqcs6() == null : this.getAqcs6().equals(other.getAqcs6()))
            && (this.getAqcs7() == null ? other.getAqcs7() == null : this.getAqcs7().equals(other.getAqcs7()))
            && (this.getAqcs8() == null ? other.getAqcs8() == null : this.getAqcs8().equals(other.getAqcs8()))
            && (this.getAqcs9() == null ? other.getAqcs9() == null : this.getAqcs9().equals(other.getAqcs9()))
            && (this.getZycs1() == null ? other.getZycs1() == null : this.getZycs1().equals(other.getZycs1()))
            && (this.getZycs2() == null ? other.getZycs2() == null : this.getZycs2().equals(other.getZycs2()))
            && (this.getZycs3() == null ? other.getZycs3() == null : this.getZycs3().equals(other.getZycs3()))
            && (this.getZycs4() == null ? other.getZycs4() == null : this.getZycs4().equals(other.getZycs4()))
            && (this.getZycs5() == null ? other.getZycs5() == null : this.getZycs5().equals(other.getZycs5()))
            && (this.getZycs6() == null ? other.getZycs6() == null : this.getZycs6().equals(other.getZycs6()))
            && (this.getZycs7() == null ? other.getZycs7() == null : this.getZycs7().equals(other.getZycs7()))
            && (this.getZycs8() == null ? other.getZycs8() == null : this.getZycs8().equals(other.getZycs8()))
            && (this.getZycs9() == null ? other.getZycs9() == null : this.getZycs9().equals(other.getZycs9()))
            && (this.getJcry() == null ? other.getJcry() == null : this.getJcry().equals(other.getJcry()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getAqcs1() == null) ? 0 : getAqcs1().hashCode());
        result = prime * result + ((getAqcs2() == null) ? 0 : getAqcs2().hashCode());
        result = prime * result + ((getAqcs3() == null) ? 0 : getAqcs3().hashCode());
        result = prime * result + ((getAqcs4() == null) ? 0 : getAqcs4().hashCode());
        result = prime * result + ((getAqcs5() == null) ? 0 : getAqcs5().hashCode());
        result = prime * result + ((getAqcs6() == null) ? 0 : getAqcs6().hashCode());
        result = prime * result + ((getAqcs7() == null) ? 0 : getAqcs7().hashCode());
        result = prime * result + ((getAqcs8() == null) ? 0 : getAqcs8().hashCode());
        result = prime * result + ((getAqcs9() == null) ? 0 : getAqcs9().hashCode());
        result = prime * result + ((getZycs1() == null) ? 0 : getZycs1().hashCode());
        result = prime * result + ((getZycs2() == null) ? 0 : getZycs2().hashCode());
        result = prime * result + ((getZycs3() == null) ? 0 : getZycs3().hashCode());
        result = prime * result + ((getZycs4() == null) ? 0 : getZycs4().hashCode());
        result = prime * result + ((getZycs5() == null) ? 0 : getZycs5().hashCode());
        result = prime * result + ((getZycs6() == null) ? 0 : getZycs6().hashCode());
        result = prime * result + ((getZycs7() == null) ? 0 : getZycs7().hashCode());
        result = prime * result + ((getZycs8() == null) ? 0 : getZycs8().hashCode());
        result = prime * result + ((getZycs9() == null) ? 0 : getZycs9().hashCode());
        result = prime * result + ((getJcry() == null) ? 0 : getJcry().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_liquidammonia_permit_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", aqcs1=").append(aqcs1);
        sb.append(", aqcs2=").append(aqcs2);
        sb.append(", aqcs3=").append(aqcs3);
        sb.append(", aqcs4=").append(aqcs4);
        sb.append(", aqcs5=").append(aqcs5);
        sb.append(", aqcs6=").append(aqcs6);
        sb.append(", aqcs7=").append(aqcs7);
        sb.append(", aqcs8=").append(aqcs8);
        sb.append(", aqcs9=").append(aqcs9);
        sb.append(", zycs1=").append(zycs1);
        sb.append(", zycs2=").append(zycs2);
        sb.append(", zycs3=").append(zycs3);
        sb.append(", zycs4=").append(zycs4);
        sb.append(", zycs5=").append(zycs5);
        sb.append(", zycs6=").append(zycs6);
        sb.append(", zycs7=").append(zycs7);
        sb.append(", zycs8=").append(zycs8);
        sb.append(", zycs9=").append(zycs9);
        sb.append(", jcry=").append(jcry);
        sb.append(", del=").append(del);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }
}