package com.spring.web.model;

import java.util.Date;

public class YzStaff {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.ctime
	 * @mbggenerated
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.utime
	 * @mbggenerated
	 */
	private Date utime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.del
	 * @mbggenerated
	 */
	private Integer del;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.cid
	 * @mbggenerated
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.dpid
	 * @mbggenerated
	 */
	private Integer dpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.dpname
	 * @mbggenerated
	 */
	private String dpname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.post
	 * @mbggenerated
	 */
	private String post;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.position
	 * @mbggenerated
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_staff_t.uid
	 * @mbggenerated
	 */
	private Integer uid;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_staff_t
	 * @mbggenerated
	 */
	public YzStaff(Integer id, Date ctime, Date utime, Integer del,
			String name, String mobile, Integer cid, Integer dpid,
			String dpname, String post, String position, String remark,
			Integer uid) {
		this.id = id;
		this.ctime = ctime;
		this.utime = utime;
		this.del = del;
		this.name = name;
		this.mobile = mobile;
		this.cid = cid;
		this.dpid = dpid;
		this.dpname = dpname;
		this.post = post;
		this.position = position;
		this.remark = remark;
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_staff_t
	 * @mbggenerated
	 */
	public YzStaff() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.id
	 * @return  the value of yz_staff_t.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.id
	 * @param id  the value for yz_staff_t.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.ctime
	 * @return  the value of yz_staff_t.ctime
	 * @mbggenerated
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.ctime
	 * @param ctime  the value for yz_staff_t.ctime
	 * @mbggenerated
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.utime
	 * @return  the value of yz_staff_t.utime
	 * @mbggenerated
	 */
	public Date getUtime() {
		return utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.utime
	 * @param utime  the value for yz_staff_t.utime
	 * @mbggenerated
	 */
	public void setUtime(Date utime) {
		this.utime = utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.del
	 * @return  the value of yz_staff_t.del
	 * @mbggenerated
	 */
	public Integer getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.del
	 * @param del  the value for yz_staff_t.del
	 * @mbggenerated
	 */
	public void setDel(Integer del) {
		this.del = del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.name
	 * @return  the value of yz_staff_t.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.name
	 * @param name  the value for yz_staff_t.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.mobile
	 * @return  the value of yz_staff_t.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.mobile
	 * @param mobile  the value for yz_staff_t.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.cid
	 * @return  the value of yz_staff_t.cid
	 * @mbggenerated
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.cid
	 * @param cid  the value for yz_staff_t.cid
	 * @mbggenerated
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.dpid
	 * @return  the value of yz_staff_t.dpid
	 * @mbggenerated
	 */
	public Integer getDpid() {
		return dpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.dpid
	 * @param dpid  the value for yz_staff_t.dpid
	 * @mbggenerated
	 */
	public void setDpid(Integer dpid) {
		this.dpid = dpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.dpname
	 * @return  the value of yz_staff_t.dpname
	 * @mbggenerated
	 */
	public String getDpname() {
		return dpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.dpname
	 * @param dpname  the value for yz_staff_t.dpname
	 * @mbggenerated
	 */
	public void setDpname(String dpname) {
		this.dpname = dpname == null ? null : dpname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.post
	 * @return  the value of yz_staff_t.post
	 * @mbggenerated
	 */
	public String getPost() {
		return post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.post
	 * @param post  the value for yz_staff_t.post
	 * @mbggenerated
	 */
	public void setPost(String post) {
		this.post = post == null ? null : post.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.position
	 * @return  the value of yz_staff_t.position
	 * @mbggenerated
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.position
	 * @param position  the value for yz_staff_t.position
	 * @mbggenerated
	 */
	public void setPosition(String position) {
		this.position = position == null ? null : position.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.remark
	 * @return  the value of yz_staff_t.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.remark
	 * @param remark  the value for yz_staff_t.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_staff_t.uid
	 * @return  the value of yz_staff_t.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_staff_t.uid
	 * @param uid  the value for yz_staff_t.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_staff_t
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		YzStaff other = (YzStaff) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getCtime() == null ? other.getCtime() == null : this
						.getCtime().equals(other.getCtime()))
				&& (this.getUtime() == null ? other.getUtime() == null : this
						.getUtime().equals(other.getUtime()))
				&& (this.getDel() == null ? other.getDel() == null : this
						.getDel().equals(other.getDel()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getMobile() == null ? other.getMobile() == null : this
						.getMobile().equals(other.getMobile()))
				&& (this.getCid() == null ? other.getCid() == null : this
						.getCid().equals(other.getCid()))
				&& (this.getDpid() == null ? other.getDpid() == null : this
						.getDpid().equals(other.getDpid()))
				&& (this.getDpname() == null ? other.getDpname() == null : this
						.getDpname().equals(other.getDpname()))
				&& (this.getPost() == null ? other.getPost() == null : this
						.getPost().equals(other.getPost()))
				&& (this.getPosition() == null ? other.getPosition() == null
						: this.getPosition().equals(other.getPosition()))
				&& (this.getRemark() == null ? other.getRemark() == null : this
						.getRemark().equals(other.getRemark()))
				&& (this.getUid() == null ? other.getUid() == null : this
						.getUid().equals(other.getUid()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_staff_t
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getCtime() == null) ? 0 : getCtime().hashCode());
		result = prime * result
				+ ((getUtime() == null) ? 0 : getUtime().hashCode());
		result = prime * result
				+ ((getDel() == null) ? 0 : getDel().hashCode());
		result = prime * result
				+ ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result
				+ ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result
				+ ((getCid() == null) ? 0 : getCid().hashCode());
		result = prime * result
				+ ((getDpid() == null) ? 0 : getDpid().hashCode());
		result = prime * result
				+ ((getDpname() == null) ? 0 : getDpname().hashCode());
		result = prime * result
				+ ((getPost() == null) ? 0 : getPost().hashCode());
		result = prime * result
				+ ((getPosition() == null) ? 0 : getPosition().hashCode());
		result = prime * result
				+ ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result
				+ ((getUid() == null) ? 0 : getUid().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_staff_t
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", ctime=").append(ctime);
		sb.append(", utime=").append(utime);
		sb.append(", del=").append(del);
		sb.append(", name=").append(name);
		sb.append(", mobile=").append(mobile);
		sb.append(", cid=").append(cid);
		sb.append(", dpid=").append(dpid);
		sb.append(", dpname=").append(dpname);
		sb.append(", post=").append(post);
		sb.append(", position=").append(position);
		sb.append(", remark=").append(remark);
		sb.append(", uid=").append(uid);
		sb.append("]");
		return sb.toString();
	}
}