package com.spring.web.model;

import java.util.Date;

public class YzStiveExplosion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy11
     *
     * @mbggenerated
     */
    private String fcsbqy11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy21
     *
     * @mbggenerated
     */
    private String fcsbqy21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy22
     *
     * @mbggenerated
     */
    private String fcsbqy22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy23
     *
     * @mbggenerated
     */
    private String fcsbqy23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy31
     *
     * @mbggenerated
     */
    private String fcsbqy31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy32
     *
     * @mbggenerated
     */
    private String fcsbqy32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy41
     *
     * @mbggenerated
     */
    private String fcsbqy41;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy42
     *
     * @mbggenerated
     */
    private String fcsbqy42;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy43
     *
     * @mbggenerated
     */
    private String fcsbqy43;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy44
     *
     * @mbggenerated
     */
    private String fcsbqy44;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy45
     *
     * @mbggenerated
     */
    private String fcsbqy45;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy51
     *
     * @mbggenerated
     */
    private String fcsbqy51;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy52
     *
     * @mbggenerated
     */
    private String fcsbqy52;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy61
     *
     * @mbggenerated
     */
    private String fcsbqy61;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy71
     *
     * @mbggenerated
     */
    private String fcsbqy71;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy81
     *
     * @mbggenerated
     */
    private String fcsbqy81;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy82
     *
     * @mbggenerated
     */
    private String fcsbqy82;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy91
     *
     * @mbggenerated
     */
    private String fcsbqy91;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy92
     *
     * @mbggenerated
     */
    private String fcsbqy92;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.fcsbqy93
     *
     * @mbggenerated
     */
    private String fcsbqy93;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.jcry
     *
     * @mbggenerated
     */
    private String jcry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_stiveexplosion_permit_t.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_stiveexplosion_permit_t
     *
     * @mbggenerated
     */
    public YzStiveExplosion(Integer id, Integer uid, String fcsbqy11, String fcsbqy21, String fcsbqy22, String fcsbqy23, String fcsbqy31, String fcsbqy32, String fcsbqy41, String fcsbqy42, String fcsbqy43, String fcsbqy44, String fcsbqy45, String fcsbqy51, String fcsbqy52, String fcsbqy61, String fcsbqy71, String fcsbqy81, String fcsbqy82, String fcsbqy91, String fcsbqy92, String fcsbqy93, String jcry, Integer del, Date ctime) {
        this.id = id;
        this.uid = uid;
        this.fcsbqy11 = fcsbqy11;
        this.fcsbqy21 = fcsbqy21;
        this.fcsbqy22 = fcsbqy22;
        this.fcsbqy23 = fcsbqy23;
        this.fcsbqy31 = fcsbqy31;
        this.fcsbqy32 = fcsbqy32;
        this.fcsbqy41 = fcsbqy41;
        this.fcsbqy42 = fcsbqy42;
        this.fcsbqy43 = fcsbqy43;
        this.fcsbqy44 = fcsbqy44;
        this.fcsbqy45 = fcsbqy45;
        this.fcsbqy51 = fcsbqy51;
        this.fcsbqy52 = fcsbqy52;
        this.fcsbqy61 = fcsbqy61;
        this.fcsbqy71 = fcsbqy71;
        this.fcsbqy81 = fcsbqy81;
        this.fcsbqy82 = fcsbqy82;
        this.fcsbqy91 = fcsbqy91;
        this.fcsbqy92 = fcsbqy92;
        this.fcsbqy93 = fcsbqy93;
        this.jcry = jcry;
        this.del = del;
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_stiveexplosion_permit_t
     *
     * @mbggenerated
     */
    public YzStiveExplosion() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.id
     *
     * @return the value of yz_stiveexplosion_permit_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.id
     *
     * @param id the value for yz_stiveexplosion_permit_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.uid
     *
     * @return the value of yz_stiveexplosion_permit_t.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.uid
     *
     * @param uid the value for yz_stiveexplosion_permit_t.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy11
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy11
     *
     * @mbggenerated
     */
    public String getFcsbqy11() {
        return fcsbqy11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy11
     *
     * @param fcsbqy11 the value for yz_stiveexplosion_permit_t.fcsbqy11
     *
     * @mbggenerated
     */
    public void setFcsbqy11(String fcsbqy11) {
        this.fcsbqy11 = fcsbqy11 == null ? null : fcsbqy11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy21
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy21
     *
     * @mbggenerated
     */
    public String getFcsbqy21() {
        return fcsbqy21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy21
     *
     * @param fcsbqy21 the value for yz_stiveexplosion_permit_t.fcsbqy21
     *
     * @mbggenerated
     */
    public void setFcsbqy21(String fcsbqy21) {
        this.fcsbqy21 = fcsbqy21 == null ? null : fcsbqy21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy22
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy22
     *
     * @mbggenerated
     */
    public String getFcsbqy22() {
        return fcsbqy22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy22
     *
     * @param fcsbqy22 the value for yz_stiveexplosion_permit_t.fcsbqy22
     *
     * @mbggenerated
     */
    public void setFcsbqy22(String fcsbqy22) {
        this.fcsbqy22 = fcsbqy22 == null ? null : fcsbqy22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy23
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy23
     *
     * @mbggenerated
     */
    public String getFcsbqy23() {
        return fcsbqy23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy23
     *
     * @param fcsbqy23 the value for yz_stiveexplosion_permit_t.fcsbqy23
     *
     * @mbggenerated
     */
    public void setFcsbqy23(String fcsbqy23) {
        this.fcsbqy23 = fcsbqy23 == null ? null : fcsbqy23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy31
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy31
     *
     * @mbggenerated
     */
    public String getFcsbqy31() {
        return fcsbqy31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy31
     *
     * @param fcsbqy31 the value for yz_stiveexplosion_permit_t.fcsbqy31
     *
     * @mbggenerated
     */
    public void setFcsbqy31(String fcsbqy31) {
        this.fcsbqy31 = fcsbqy31 == null ? null : fcsbqy31.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy32
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy32
     *
     * @mbggenerated
     */
    public String getFcsbqy32() {
        return fcsbqy32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy32
     *
     * @param fcsbqy32 the value for yz_stiveexplosion_permit_t.fcsbqy32
     *
     * @mbggenerated
     */
    public void setFcsbqy32(String fcsbqy32) {
        this.fcsbqy32 = fcsbqy32 == null ? null : fcsbqy32.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy41
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy41
     *
     * @mbggenerated
     */
    public String getFcsbqy41() {
        return fcsbqy41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy41
     *
     * @param fcsbqy41 the value for yz_stiveexplosion_permit_t.fcsbqy41
     *
     * @mbggenerated
     */
    public void setFcsbqy41(String fcsbqy41) {
        this.fcsbqy41 = fcsbqy41 == null ? null : fcsbqy41.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy42
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy42
     *
     * @mbggenerated
     */
    public String getFcsbqy42() {
        return fcsbqy42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy42
     *
     * @param fcsbqy42 the value for yz_stiveexplosion_permit_t.fcsbqy42
     *
     * @mbggenerated
     */
    public void setFcsbqy42(String fcsbqy42) {
        this.fcsbqy42 = fcsbqy42 == null ? null : fcsbqy42.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy43
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy43
     *
     * @mbggenerated
     */
    public String getFcsbqy43() {
        return fcsbqy43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy43
     *
     * @param fcsbqy43 the value for yz_stiveexplosion_permit_t.fcsbqy43
     *
     * @mbggenerated
     */
    public void setFcsbqy43(String fcsbqy43) {
        this.fcsbqy43 = fcsbqy43 == null ? null : fcsbqy43.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy44
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy44
     *
     * @mbggenerated
     */
    public String getFcsbqy44() {
        return fcsbqy44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy44
     *
     * @param fcsbqy44 the value for yz_stiveexplosion_permit_t.fcsbqy44
     *
     * @mbggenerated
     */
    public void setFcsbqy44(String fcsbqy44) {
        this.fcsbqy44 = fcsbqy44 == null ? null : fcsbqy44.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy45
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy45
     *
     * @mbggenerated
     */
    public String getFcsbqy45() {
        return fcsbqy45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy45
     *
     * @param fcsbqy45 the value for yz_stiveexplosion_permit_t.fcsbqy45
     *
     * @mbggenerated
     */
    public void setFcsbqy45(String fcsbqy45) {
        this.fcsbqy45 = fcsbqy45 == null ? null : fcsbqy45.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy51
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy51
     *
     * @mbggenerated
     */
    public String getFcsbqy51() {
        return fcsbqy51;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy51
     *
     * @param fcsbqy51 the value for yz_stiveexplosion_permit_t.fcsbqy51
     *
     * @mbggenerated
     */
    public void setFcsbqy51(String fcsbqy51) {
        this.fcsbqy51 = fcsbqy51 == null ? null : fcsbqy51.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy52
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy52
     *
     * @mbggenerated
     */
    public String getFcsbqy52() {
        return fcsbqy52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy52
     *
     * @param fcsbqy52 the value for yz_stiveexplosion_permit_t.fcsbqy52
     *
     * @mbggenerated
     */
    public void setFcsbqy52(String fcsbqy52) {
        this.fcsbqy52 = fcsbqy52 == null ? null : fcsbqy52.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy61
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy61
     *
     * @mbggenerated
     */
    public String getFcsbqy61() {
        return fcsbqy61;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy61
     *
     * @param fcsbqy61 the value for yz_stiveexplosion_permit_t.fcsbqy61
     *
     * @mbggenerated
     */
    public void setFcsbqy61(String fcsbqy61) {
        this.fcsbqy61 = fcsbqy61 == null ? null : fcsbqy61.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy71
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy71
     *
     * @mbggenerated
     */
    public String getFcsbqy71() {
        return fcsbqy71;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy71
     *
     * @param fcsbqy71 the value for yz_stiveexplosion_permit_t.fcsbqy71
     *
     * @mbggenerated
     */
    public void setFcsbqy71(String fcsbqy71) {
        this.fcsbqy71 = fcsbqy71 == null ? null : fcsbqy71.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy81
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy81
     *
     * @mbggenerated
     */
    public String getFcsbqy81() {
        return fcsbqy81;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy81
     *
     * @param fcsbqy81 the value for yz_stiveexplosion_permit_t.fcsbqy81
     *
     * @mbggenerated
     */
    public void setFcsbqy81(String fcsbqy81) {
        this.fcsbqy81 = fcsbqy81 == null ? null : fcsbqy81.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy82
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy82
     *
     * @mbggenerated
     */
    public String getFcsbqy82() {
        return fcsbqy82;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy82
     *
     * @param fcsbqy82 the value for yz_stiveexplosion_permit_t.fcsbqy82
     *
     * @mbggenerated
     */
    public void setFcsbqy82(String fcsbqy82) {
        this.fcsbqy82 = fcsbqy82 == null ? null : fcsbqy82.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy91
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy91
     *
     * @mbggenerated
     */
    public String getFcsbqy91() {
        return fcsbqy91;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy91
     *
     * @param fcsbqy91 the value for yz_stiveexplosion_permit_t.fcsbqy91
     *
     * @mbggenerated
     */
    public void setFcsbqy91(String fcsbqy91) {
        this.fcsbqy91 = fcsbqy91 == null ? null : fcsbqy91.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy92
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy92
     *
     * @mbggenerated
     */
    public String getFcsbqy92() {
        return fcsbqy92;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy92
     *
     * @param fcsbqy92 the value for yz_stiveexplosion_permit_t.fcsbqy92
     *
     * @mbggenerated
     */
    public void setFcsbqy92(String fcsbqy92) {
        this.fcsbqy92 = fcsbqy92 == null ? null : fcsbqy92.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.fcsbqy93
     *
     * @return the value of yz_stiveexplosion_permit_t.fcsbqy93
     *
     * @mbggenerated
     */
    public String getFcsbqy93() {
        return fcsbqy93;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.fcsbqy93
     *
     * @param fcsbqy93 the value for yz_stiveexplosion_permit_t.fcsbqy93
     *
     * @mbggenerated
     */
    public void setFcsbqy93(String fcsbqy93) {
        this.fcsbqy93 = fcsbqy93 == null ? null : fcsbqy93.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.jcry
     *
     * @return the value of yz_stiveexplosion_permit_t.jcry
     *
     * @mbggenerated
     */
    public String getJcry() {
        return jcry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.jcry
     *
     * @param jcry the value for yz_stiveexplosion_permit_t.jcry
     *
     * @mbggenerated
     */
    public void setJcry(String jcry) {
        this.jcry = jcry == null ? null : jcry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.del
     *
     * @return the value of yz_stiveexplosion_permit_t.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.del
     *
     * @param del the value for yz_stiveexplosion_permit_t.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_stiveexplosion_permit_t.ctime
     *
     * @return the value of yz_stiveexplosion_permit_t.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_stiveexplosion_permit_t.ctime
     *
     * @param ctime the value for yz_stiveexplosion_permit_t.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_stiveexplosion_permit_t
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YzStiveExplosion other = (YzStiveExplosion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getFcsbqy11() == null ? other.getFcsbqy11() == null : this.getFcsbqy11().equals(other.getFcsbqy11()))
            && (this.getFcsbqy21() == null ? other.getFcsbqy21() == null : this.getFcsbqy21().equals(other.getFcsbqy21()))
            && (this.getFcsbqy22() == null ? other.getFcsbqy22() == null : this.getFcsbqy22().equals(other.getFcsbqy22()))
            && (this.getFcsbqy23() == null ? other.getFcsbqy23() == null : this.getFcsbqy23().equals(other.getFcsbqy23()))
            && (this.getFcsbqy31() == null ? other.getFcsbqy31() == null : this.getFcsbqy31().equals(other.getFcsbqy31()))
            && (this.getFcsbqy32() == null ? other.getFcsbqy32() == null : this.getFcsbqy32().equals(other.getFcsbqy32()))
            && (this.getFcsbqy41() == null ? other.getFcsbqy41() == null : this.getFcsbqy41().equals(other.getFcsbqy41()))
            && (this.getFcsbqy42() == null ? other.getFcsbqy42() == null : this.getFcsbqy42().equals(other.getFcsbqy42()))
            && (this.getFcsbqy43() == null ? other.getFcsbqy43() == null : this.getFcsbqy43().equals(other.getFcsbqy43()))
            && (this.getFcsbqy44() == null ? other.getFcsbqy44() == null : this.getFcsbqy44().equals(other.getFcsbqy44()))
            && (this.getFcsbqy45() == null ? other.getFcsbqy45() == null : this.getFcsbqy45().equals(other.getFcsbqy45()))
            && (this.getFcsbqy51() == null ? other.getFcsbqy51() == null : this.getFcsbqy51().equals(other.getFcsbqy51()))
            && (this.getFcsbqy52() == null ? other.getFcsbqy52() == null : this.getFcsbqy52().equals(other.getFcsbqy52()))
            && (this.getFcsbqy61() == null ? other.getFcsbqy61() == null : this.getFcsbqy61().equals(other.getFcsbqy61()))
            && (this.getFcsbqy71() == null ? other.getFcsbqy71() == null : this.getFcsbqy71().equals(other.getFcsbqy71()))
            && (this.getFcsbqy81() == null ? other.getFcsbqy81() == null : this.getFcsbqy81().equals(other.getFcsbqy81()))
            && (this.getFcsbqy82() == null ? other.getFcsbqy82() == null : this.getFcsbqy82().equals(other.getFcsbqy82()))
            && (this.getFcsbqy91() == null ? other.getFcsbqy91() == null : this.getFcsbqy91().equals(other.getFcsbqy91()))
            && (this.getFcsbqy92() == null ? other.getFcsbqy92() == null : this.getFcsbqy92().equals(other.getFcsbqy92()))
            && (this.getFcsbqy93() == null ? other.getFcsbqy93() == null : this.getFcsbqy93().equals(other.getFcsbqy93()))
            && (this.getJcry() == null ? other.getJcry() == null : this.getJcry().equals(other.getJcry()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_stiveexplosion_permit_t
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getFcsbqy11() == null) ? 0 : getFcsbqy11().hashCode());
        result = prime * result + ((getFcsbqy21() == null) ? 0 : getFcsbqy21().hashCode());
        result = prime * result + ((getFcsbqy22() == null) ? 0 : getFcsbqy22().hashCode());
        result = prime * result + ((getFcsbqy23() == null) ? 0 : getFcsbqy23().hashCode());
        result = prime * result + ((getFcsbqy31() == null) ? 0 : getFcsbqy31().hashCode());
        result = prime * result + ((getFcsbqy32() == null) ? 0 : getFcsbqy32().hashCode());
        result = prime * result + ((getFcsbqy41() == null) ? 0 : getFcsbqy41().hashCode());
        result = prime * result + ((getFcsbqy42() == null) ? 0 : getFcsbqy42().hashCode());
        result = prime * result + ((getFcsbqy43() == null) ? 0 : getFcsbqy43().hashCode());
        result = prime * result + ((getFcsbqy44() == null) ? 0 : getFcsbqy44().hashCode());
        result = prime * result + ((getFcsbqy45() == null) ? 0 : getFcsbqy45().hashCode());
        result = prime * result + ((getFcsbqy51() == null) ? 0 : getFcsbqy51().hashCode());
        result = prime * result + ((getFcsbqy52() == null) ? 0 : getFcsbqy52().hashCode());
        result = prime * result + ((getFcsbqy61() == null) ? 0 : getFcsbqy61().hashCode());
        result = prime * result + ((getFcsbqy71() == null) ? 0 : getFcsbqy71().hashCode());
        result = prime * result + ((getFcsbqy81() == null) ? 0 : getFcsbqy81().hashCode());
        result = prime * result + ((getFcsbqy82() == null) ? 0 : getFcsbqy82().hashCode());
        result = prime * result + ((getFcsbqy91() == null) ? 0 : getFcsbqy91().hashCode());
        result = prime * result + ((getFcsbqy92() == null) ? 0 : getFcsbqy92().hashCode());
        result = prime * result + ((getFcsbqy93() == null) ? 0 : getFcsbqy93().hashCode());
        result = prime * result + ((getJcry() == null) ? 0 : getJcry().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yz_stiveexplosion_permit_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", fcsbqy11=").append(fcsbqy11);
        sb.append(", fcsbqy21=").append(fcsbqy21);
        sb.append(", fcsbqy22=").append(fcsbqy22);
        sb.append(", fcsbqy23=").append(fcsbqy23);
        sb.append(", fcsbqy31=").append(fcsbqy31);
        sb.append(", fcsbqy32=").append(fcsbqy32);
        sb.append(", fcsbqy41=").append(fcsbqy41);
        sb.append(", fcsbqy42=").append(fcsbqy42);
        sb.append(", fcsbqy43=").append(fcsbqy43);
        sb.append(", fcsbqy44=").append(fcsbqy44);
        sb.append(", fcsbqy45=").append(fcsbqy45);
        sb.append(", fcsbqy51=").append(fcsbqy51);
        sb.append(", fcsbqy52=").append(fcsbqy52);
        sb.append(", fcsbqy61=").append(fcsbqy61);
        sb.append(", fcsbqy71=").append(fcsbqy71);
        sb.append(", fcsbqy81=").append(fcsbqy81);
        sb.append(", fcsbqy82=").append(fcsbqy82);
        sb.append(", fcsbqy91=").append(fcsbqy91);
        sb.append(", fcsbqy92=").append(fcsbqy92);
        sb.append(", fcsbqy93=").append(fcsbqy93);
        sb.append(", jcry=").append(jcry);
        sb.append(", del=").append(del);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }
}