package com.spring.web.model;

import java.util.Date;

public class YzTradeArder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl1
	 * @mbggenerated
	 */
	private String zyxcgl1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl2
	 * @mbggenerated
	 */
	private String zyxcgl2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl3
	 * @mbggenerated
	 */
	private String zyxcgl3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl4
	 * @mbggenerated
	 */
	private String zyxcgl4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl5
	 * @mbggenerated
	 */
	private String zyxcgl5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl6
	 * @mbggenerated
	 */
	private String zyxcgl6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl7
	 * @mbggenerated
	 */
	private String zyxcgl7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl8
	 * @mbggenerated
	 */
	private String zyxcgl8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.zyxcgl9
	 * @mbggenerated
	 */
	private String zyxcgl9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.jcry
	 * @mbggenerated
	 */
	private String jcry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.del
	 * @mbggenerated
	 */
	private Integer del;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yz_tradearder_permit_t.ctime
	 * @mbggenerated
	 */
	private Date ctime;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	public YzTradeArder(Integer id, Integer uid, String zyxcgl1,
			String zyxcgl2, String zyxcgl3, String zyxcgl4, String zyxcgl5,
			String zyxcgl6, String zyxcgl7, String zyxcgl8, String zyxcgl9,
			String jcry, Integer del, Date ctime) {
		this.id = id;
		this.uid = uid;
		this.zyxcgl1 = zyxcgl1;
		this.zyxcgl2 = zyxcgl2;
		this.zyxcgl3 = zyxcgl3;
		this.zyxcgl4 = zyxcgl4;
		this.zyxcgl5 = zyxcgl5;
		this.zyxcgl6 = zyxcgl6;
		this.zyxcgl7 = zyxcgl7;
		this.zyxcgl8 = zyxcgl8;
		this.zyxcgl9 = zyxcgl9;
		this.jcry = jcry;
		this.del = del;
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	public YzTradeArder() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.id
	 * @return  the value of yz_tradearder_permit_t.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.id
	 * @param id  the value for yz_tradearder_permit_t.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.uid
	 * @return  the value of yz_tradearder_permit_t.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.uid
	 * @param uid  the value for yz_tradearder_permit_t.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl1
	 * @return  the value of yz_tradearder_permit_t.zyxcgl1
	 * @mbggenerated
	 */
	public String getZyxcgl1() {
		return zyxcgl1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl1
	 * @param zyxcgl1  the value for yz_tradearder_permit_t.zyxcgl1
	 * @mbggenerated
	 */
	public void setZyxcgl1(String zyxcgl1) {
		this.zyxcgl1 = zyxcgl1 == null ? null : zyxcgl1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl2
	 * @return  the value of yz_tradearder_permit_t.zyxcgl2
	 * @mbggenerated
	 */
	public String getZyxcgl2() {
		return zyxcgl2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl2
	 * @param zyxcgl2  the value for yz_tradearder_permit_t.zyxcgl2
	 * @mbggenerated
	 */
	public void setZyxcgl2(String zyxcgl2) {
		this.zyxcgl2 = zyxcgl2 == null ? null : zyxcgl2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl3
	 * @return  the value of yz_tradearder_permit_t.zyxcgl3
	 * @mbggenerated
	 */
	public String getZyxcgl3() {
		return zyxcgl3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl3
	 * @param zyxcgl3  the value for yz_tradearder_permit_t.zyxcgl3
	 * @mbggenerated
	 */
	public void setZyxcgl3(String zyxcgl3) {
		this.zyxcgl3 = zyxcgl3 == null ? null : zyxcgl3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl4
	 * @return  the value of yz_tradearder_permit_t.zyxcgl4
	 * @mbggenerated
	 */
	public String getZyxcgl4() {
		return zyxcgl4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl4
	 * @param zyxcgl4  the value for yz_tradearder_permit_t.zyxcgl4
	 * @mbggenerated
	 */
	public void setZyxcgl4(String zyxcgl4) {
		this.zyxcgl4 = zyxcgl4 == null ? null : zyxcgl4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl5
	 * @return  the value of yz_tradearder_permit_t.zyxcgl5
	 * @mbggenerated
	 */
	public String getZyxcgl5() {
		return zyxcgl5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl5
	 * @param zyxcgl5  the value for yz_tradearder_permit_t.zyxcgl5
	 * @mbggenerated
	 */
	public void setZyxcgl5(String zyxcgl5) {
		this.zyxcgl5 = zyxcgl5 == null ? null : zyxcgl5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl6
	 * @return  the value of yz_tradearder_permit_t.zyxcgl6
	 * @mbggenerated
	 */
	public String getZyxcgl6() {
		return zyxcgl6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl6
	 * @param zyxcgl6  the value for yz_tradearder_permit_t.zyxcgl6
	 * @mbggenerated
	 */
	public void setZyxcgl6(String zyxcgl6) {
		this.zyxcgl6 = zyxcgl6 == null ? null : zyxcgl6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl7
	 * @return  the value of yz_tradearder_permit_t.zyxcgl7
	 * @mbggenerated
	 */
	public String getZyxcgl7() {
		return zyxcgl7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl7
	 * @param zyxcgl7  the value for yz_tradearder_permit_t.zyxcgl7
	 * @mbggenerated
	 */
	public void setZyxcgl7(String zyxcgl7) {
		this.zyxcgl7 = zyxcgl7 == null ? null : zyxcgl7.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl8
	 * @return  the value of yz_tradearder_permit_t.zyxcgl8
	 * @mbggenerated
	 */
	public String getZyxcgl8() {
		return zyxcgl8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl8
	 * @param zyxcgl8  the value for yz_tradearder_permit_t.zyxcgl8
	 * @mbggenerated
	 */
	public void setZyxcgl8(String zyxcgl8) {
		this.zyxcgl8 = zyxcgl8 == null ? null : zyxcgl8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.zyxcgl9
	 * @return  the value of yz_tradearder_permit_t.zyxcgl9
	 * @mbggenerated
	 */
	public String getZyxcgl9() {
		return zyxcgl9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.zyxcgl9
	 * @param zyxcgl9  the value for yz_tradearder_permit_t.zyxcgl9
	 * @mbggenerated
	 */
	public void setZyxcgl9(String zyxcgl9) {
		this.zyxcgl9 = zyxcgl9 == null ? null : zyxcgl9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.jcry
	 * @return  the value of yz_tradearder_permit_t.jcry
	 * @mbggenerated
	 */
	public String getJcry() {
		return jcry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.jcry
	 * @param jcry  the value for yz_tradearder_permit_t.jcry
	 * @mbggenerated
	 */
	public void setJcry(String jcry) {
		this.jcry = jcry == null ? null : jcry.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.del
	 * @return  the value of yz_tradearder_permit_t.del
	 * @mbggenerated
	 */
	public Integer getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.del
	 * @param del  the value for yz_tradearder_permit_t.del
	 * @mbggenerated
	 */
	public void setDel(Integer del) {
		this.del = del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yz_tradearder_permit_t.ctime
	 * @return  the value of yz_tradearder_permit_t.ctime
	 * @mbggenerated
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yz_tradearder_permit_t.ctime
	 * @param ctime  the value for yz_tradearder_permit_t.ctime
	 * @mbggenerated
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		YzTradeArder other = (YzTradeArder) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getUid() == null ? other.getUid() == null : this
						.getUid().equals(other.getUid()))
				&& (this.getZyxcgl1() == null ? other.getZyxcgl1() == null
						: this.getZyxcgl1().equals(other.getZyxcgl1()))
				&& (this.getZyxcgl2() == null ? other.getZyxcgl2() == null
						: this.getZyxcgl2().equals(other.getZyxcgl2()))
				&& (this.getZyxcgl3() == null ? other.getZyxcgl3() == null
						: this.getZyxcgl3().equals(other.getZyxcgl3()))
				&& (this.getZyxcgl4() == null ? other.getZyxcgl4() == null
						: this.getZyxcgl4().equals(other.getZyxcgl4()))
				&& (this.getZyxcgl5() == null ? other.getZyxcgl5() == null
						: this.getZyxcgl5().equals(other.getZyxcgl5()))
				&& (this.getZyxcgl6() == null ? other.getZyxcgl6() == null
						: this.getZyxcgl6().equals(other.getZyxcgl6()))
				&& (this.getZyxcgl7() == null ? other.getZyxcgl7() == null
						: this.getZyxcgl7().equals(other.getZyxcgl7()))
				&& (this.getZyxcgl8() == null ? other.getZyxcgl8() == null
						: this.getZyxcgl8().equals(other.getZyxcgl8()))
				&& (this.getZyxcgl9() == null ? other.getZyxcgl9() == null
						: this.getZyxcgl9().equals(other.getZyxcgl9()))
				&& (this.getJcry() == null ? other.getJcry() == null : this
						.getJcry().equals(other.getJcry()))
				&& (this.getDel() == null ? other.getDel() == null : this
						.getDel().equals(other.getDel()))
				&& (this.getCtime() == null ? other.getCtime() == null : this
						.getCtime().equals(other.getCtime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getUid() == null) ? 0 : getUid().hashCode());
		result = prime * result
				+ ((getZyxcgl1() == null) ? 0 : getZyxcgl1().hashCode());
		result = prime * result
				+ ((getZyxcgl2() == null) ? 0 : getZyxcgl2().hashCode());
		result = prime * result
				+ ((getZyxcgl3() == null) ? 0 : getZyxcgl3().hashCode());
		result = prime * result
				+ ((getZyxcgl4() == null) ? 0 : getZyxcgl4().hashCode());
		result = prime * result
				+ ((getZyxcgl5() == null) ? 0 : getZyxcgl5().hashCode());
		result = prime * result
				+ ((getZyxcgl6() == null) ? 0 : getZyxcgl6().hashCode());
		result = prime * result
				+ ((getZyxcgl7() == null) ? 0 : getZyxcgl7().hashCode());
		result = prime * result
				+ ((getZyxcgl8() == null) ? 0 : getZyxcgl8().hashCode());
		result = prime * result
				+ ((getZyxcgl9() == null) ? 0 : getZyxcgl9().hashCode());
		result = prime * result
				+ ((getJcry() == null) ? 0 : getJcry().hashCode());
		result = prime * result
				+ ((getDel() == null) ? 0 : getDel().hashCode());
		result = prime * result
				+ ((getCtime() == null) ? 0 : getCtime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yz_tradearder_permit_t
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", zyxcgl1=").append(zyxcgl1);
		sb.append(", zyxcgl2=").append(zyxcgl2);
		sb.append(", zyxcgl3=").append(zyxcgl3);
		sb.append(", zyxcgl4=").append(zyxcgl4);
		sb.append(", zyxcgl5=").append(zyxcgl5);
		sb.append(", zyxcgl6=").append(zyxcgl6);
		sb.append(", zyxcgl7=").append(zyxcgl7);
		sb.append(", zyxcgl8=").append(zyxcgl8);
		sb.append(", zyxcgl9=").append(zyxcgl9);
		sb.append(", jcry=").append(jcry);
		sb.append(", del=").append(del);
		sb.append(", ctime=").append(ctime);
		sb.append("]");
		return sb.toString();
	}
}