package com.spring.web.model;

import java.util.Date;

public class ZzjgPersonnel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.dpid
     *
     * @mbggenerated
     */
    private Integer dpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.did
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zzjg_personnel_tbl.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zzjg_personnel_tbl
     *
     * @mbggenerated
     */
    public ZzjgPersonnel(Integer id, Date ctime, Date utime, Integer del, String name, String mobile, String position, Integer cid, Integer dpid, Integer did, Integer uid) {
        this.id = id;
        this.ctime = ctime;
        this.utime = utime;
        this.del = del;
        this.name = name;
        this.mobile = mobile;
        this.position = position;
        this.cid = cid;
        this.dpid = dpid;
        this.did = did;
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zzjg_personnel_tbl
     *
     * @mbggenerated
     */
    public ZzjgPersonnel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.id
     *
     * @return the value of zzjg_personnel_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.id
     *
     * @param id the value for zzjg_personnel_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.ctime
     *
     * @return the value of zzjg_personnel_tbl.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.ctime
     *
     * @param ctime the value for zzjg_personnel_tbl.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.utime
     *
     * @return the value of zzjg_personnel_tbl.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.utime
     *
     * @param utime the value for zzjg_personnel_tbl.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.del
     *
     * @return the value of zzjg_personnel_tbl.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.del
     *
     * @param del the value for zzjg_personnel_tbl.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.name
     *
     * @return the value of zzjg_personnel_tbl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.name
     *
     * @param name the value for zzjg_personnel_tbl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.mobile
     *
     * @return the value of zzjg_personnel_tbl.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.mobile
     *
     * @param mobile the value for zzjg_personnel_tbl.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.position
     *
     * @return the value of zzjg_personnel_tbl.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.position
     *
     * @param position the value for zzjg_personnel_tbl.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.cid
     *
     * @return the value of zzjg_personnel_tbl.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.cid
     *
     * @param cid the value for zzjg_personnel_tbl.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.dpid
     *
     * @return the value of zzjg_personnel_tbl.dpid
     *
     * @mbggenerated
     */
    public Integer getDpid() {
        return dpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.dpid
     *
     * @param dpid the value for zzjg_personnel_tbl.dpid
     *
     * @mbggenerated
     */
    public void setDpid(Integer dpid) {
        this.dpid = dpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.did
     *
     * @return the value of zzjg_personnel_tbl.did
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.did
     *
     * @param did the value for zzjg_personnel_tbl.did
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zzjg_personnel_tbl.uid
     *
     * @return the value of zzjg_personnel_tbl.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zzjg_personnel_tbl.uid
     *
     * @param uid the value for zzjg_personnel_tbl.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zzjg_personnel_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ZzjgPersonnel other = (ZzjgPersonnel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getUtime() == null ? other.getUtime() == null : this.getUtime().equals(other.getUtime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getDpid() == null ? other.getDpid() == null : this.getDpid().equals(other.getDpid()))
            && (this.getDid() == null ? other.getDid() == null : this.getDid().equals(other.getDid()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zzjg_personnel_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getUtime() == null) ? 0 : getUtime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getDpid() == null) ? 0 : getDpid().hashCode());
        result = prime * result + ((getDid() == null) ? 0 : getDid().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zzjg_personnel_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", del=").append(del);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append(", position=").append(position);
        sb.append(", cid=").append(cid);
        sb.append(", dpid=").append(dpid);
        sb.append(", did=").append(did);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}